Add possitibility to specify an ami image for AWS
uyuni-project/sumaform pull request #1082
Opened 2022-04-07 22:14 UTC by maximenoel8

## What does this PR change?

Testing build images is currently done manually. 
This PR is part of an automation effort to test build imagefor AWS.
This PR adds the possibility to specify an image ami id for server and proxy in sumaform.

There are two main features :  
 - adding the possibility to declare an ami id in server and proxy host
 - adding the possibility to deploy without declaring repositories

2022-04-08 08:04 UTC, srbarrios commented on salt/server/testsuite.sls
> -      - sls: repos
About all the "require" sections removed.
I think we should not remove it. One thing is to include repos in the init.sls, the other to let the salt state knows that it has a dependency with repos.sls

2022-04-08 08:07 UTC, srbarrios commented on modules/proxy/variables.tf
> +}
To be consisten with the definition in the null/host module, maybe we should have here:
```
variable "ami_image" {
  description = "An ami image to overwrite the default value"
  type        = string
  default     = null
}
```

2022-04-08 08:09 UTC, srbarrios commented on modules/controller/variables.tf
> +variable "server_build_image" {
Personally I would choose a variable name that let us think this is a boolean.
Something like... "server_use_build_image"

2022-04-08 08:19 UTC, Bischoff reviewed
just a question

2022-04-08 08:19 UTC, Bischoff commented on salt/controller/bashrc
> +export SERVER_BUILD_IMAGE="{{ grains.get('server_build_image') }}"
Is it always defined ?

2022-04-08 08:34 UTC, Bischoff requested changes
Isn't this PR missing changes to README_ADVANCED.md?

2022-04-11 10:32 UTC, rjmateus requested changes
some changes that I think should be done

2022-04-11 10:32 UTC, rjmateus commented on modules/host/main.tf
> +  ami_image                     = var.ami_image
I don't think we need this, as explained above

2022-04-11 10:32 UTC, rjmateus commented on modules/proxy/main.tf
> +  ami_image                = var.ami_image
we don't need this variable

2022-04-11 10:32 UTC, rjmateus commented on modules/server/main.tf
> +  ami_image                = var.ami_image
we don't need this variable

2022-04-11 10:32 UTC, rjmateus commented on modules/server/variables.tf
> +variable "ami_image" {
we don't need this variable

2022-04-14 08:20 UTC, srbarrios commented on salt/server/testsuite.sls
> +{% endif %} {# 'build_image' not in grains.get('product_version') | default('', true) #}
I don't get why we need this comment.

2022-04-26 21:09 UTC, merged