Use generic names for RedHat and Debian-like clients
uyuni-project/sumaform pull request #1122
Opened 2022-07-04 13:13 UTC by Bischoff

## What does this PR change?

See uyuni-project/uyuni#5624

2022-07-05 10:42 UTC, ktsamis approved these changes

2022-07-05 11:06 UTC, ktsamis requested changes

2022-07-05 11:06 UTC, ktsamis commented on salt/controller/bashrc
> +{% if grains.get('debian_minion') | default(false, true) %}export DBLIKE_MINION="{{ grains.get('debian_minion') }}" {% else %}# no Debian-like minion defined {% endif %}
Are we not having RHLIKE_SSH_MINION? Or DBLIKE_SSH_MINION?

2022-07-05 12:18 UTC, Bischoff commented on salt/controller/bashrc
> +{% if grains.get('debian_minion') | default(false, true) %}export DBLIKE_MINION="{{ grains.get('debian_minion') }}" {% else %}# no Debian-like minion defined {% endif %}
No, we reuse the VM for them.

Only SLE has two VMs

2022-07-06 08:51 UTC, ktsamis approved these changes

2022-07-06 09:20 UTC, merged