Add SLES KVM virthost image template
uyuni-project/sumaform pull request #1197
Opened 2022-11-02 12:31 UTC by nodeg

## What does this PR change?

This will add a SLES 15 KVM virthost image. Later when the initial testing for SLES is done, I will also add a Debian-like and a Red Hat-like image, although I first have to find a suitable image source for that.

See https://github.com/SUSE/spacewalk/issues/17238

2022-11-02 12:52 UTC, cbosdo requested changes

2022-11-02 14:22 UTC, rjmateus commented on modules/virthost/main.tf
> +    hvm_disk_image      = var.hvm_disk_image["leap"]
I agree with Cedric here, we could just pass the map to gains, and adapt the sls accordingly.
If you prefer to keep it is fine, but we may need to refactor it in the future if more templates need to be added.

2022-11-02 14:59 UTC, nodeg commented on modules/virthost/main.tf
> +    hvm_disk_image      = var.hvm_disk_image["leap"]
I would keep it for now and adjust it when adding the Debian-like and Red Hat-like images later on.

2022-11-03 08:33 UTC, nodeg commented on modules/virthost/main.tf
> +    hvm_disk_image      = var.hvm_disk_image["leap"]
What do you think @cbosdo?

2022-11-03 08:48 UTC, cbosdo approved these changes

2022-11-03 08:48 UTC, cbosdo commented on modules/virthost/main.tf
> +    hvm_disk_image      = var.hvm_disk_image["leap"]
As you like... I would prefer doing it right from the start, but you are the one hacking it

2022-11-03 08:48 UTC, cbosdo commented on modules/virthost/variables.tf
> +  default = {
You probably want to check the CI pipelines `main.tf` files and change them if they used that variable.

2022-11-03 08:48 UTC, cbosdo commented on modules/virthost/main.tf
> +    hvm_disk_image      = var.hvm_disk_image["leap"]
Be aware also that the `leap` image here is any HVM image and could be a SLES as well for the testsuite. You probably want to clarify this in the cucumber KVM scenario

2022-11-03 10:15 UTC, nodeg commented on modules/virthost/variables.tf
> +  default = {
Normally I would also prefer doing this in the first place, but I am not that familiar with Salt states. Do you have an example on how to integrate that map into the `.sls` file?

2022-11-03 13:17 UTC, rjmateus commented on modules/virthost/variables.tf
> +  default = {
here is an example: https://github.com/uyuni-project/sumaform/blob/master/salt/default/network.sls#L13-L18

2022-11-03 14:34 UTC, nodeg commented on modules/virthost/variables.tf
> +  default = {
Thank you Ricardo, I will have a look at them.

2022-11-14 10:39 UTC, nodeg commented
@cbosdo or @rjmateus is is possible to get the FQDN/honstname from the server to insert it into my [cloud init config](https://github.com/uyuni-project/sumaform/pull/1197/files#diff-a64442233c25b8789d1acbf5f8932897e60a55bd412d84a3beb4c967ed714757R25)?

```sls
# adjust configuration files
write_files:
- content: |
   enable_legacy_startup_events: False
   enable_fqdns_grains: False
   master: # TODO FQDN server
  path: /etc/salt/minion
```
I need this for onboarding my nested VM [via the Salt OS](https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/registration-cli.html#_salt_minion_configuration) and not the bundle.

2022-11-14 12:06 UTC, cbosdo commented
> @cbosdo or @rjmateus is is possible to get the FQDN/honstname from the server to insert it into my [cloud init config](https://github.com/uyuni-project/sumaform/pull/1197/files#diff-a64442233c25b8789d1acbf5f8932897e60a55bd412d84a3beb4c967ed714757R25)?
> 
> ```yaml-salt
> # adjust configuration files
> write_files:
> - content: |
>    enable_legacy_startup_events: False
>    enable_fqdns_grains: False
>    master: # TODO FQDN server <-----------
>   path: /etc/salt/minion
> ```
> 
> I need this for onboarding my nested VM [via the Salt OS](https://documentation.suse.com/suma/4.3/en/suse-manager/client-configuration/registration-cli.html#_salt_minion_configuration) and not the bundle.

You can use `{{grains['server']}}` to get the server FQDN from the Salt states.

2022-11-18 09:34 UTC, nodeg commented on salt/virthost/cloudinit/user-data
> +  path: /etc/nsswitch.conf
Apparently only some of these changes were adapted in the VM.
Adjusted correctly:

- `/etc/salt/minion`
- `/etc/mdns.allow`

Not adjusted:

- `/etc/avahi/avahi-daemon.conf`
- `/etc/nsswitch.conf`

@cbosdo do you have any idea what the issue could be?

2022-11-22 14:15 UTC, nodeg commented
Ok. I tried several things, did several sumaform deployments and was not able to get it the way I wanted to be so I will leave it this way and maybe I or someone else can have a look in the future and improve/edit the way I did it now. I do not want to spent more time on that at the moment.
@cbosdo I had a look at the `main.tf` files in the [CI that use this variable](https://github.com/SUSE/susemanager-ci/search?q=hvm_disk_image). Since I did not change the name of the `hvm_disk_image`, the CI should be fine. I did rename the `qcow2` image file though but also renamed it in the KVM test in the testsuite: https://github.com/uyuni-project/uyuni/pull/5240/commits/d1340ab3e1731532063387802da71413867a9037
I will squash all commits before merging.
I would be glad to have another review from you @cbosdo @rjmateus.

2022-11-24 08:46 UTC, srbarrios reviewed
It looks good to me, but I would let Cedric and Ricardo to decide when this can be merged.

2022-11-24 10:42 UTC, nodeg commented on salt/virthost/cloudinit/user-data
> +   master: {{grains['server']}}
I did another local sumaform deployment to test this. Apparently this will not get replaced correctly. We run this code on the virthost and not on the server. Could that be the issue? Any suggestions?

2022-11-25 13:52 UTC, cbosdo reviewed
Raising more questions than you asked... sorry about that

2022-11-25 13:52 UTC, cbosdo commented on modules/virthost/main.tf
> +    hvm_disk_image      = var.hvm_disk_image["leap"]
you still need to get the grain as a list here

2022-11-25 13:52 UTC, cbosdo commented on salt/virthost/cloudinit/README.md
> +For mor information see the official [cloud init docs](https://cloudinit.readthedocs.io/en/latest/topics/examples.html).
```suggestion
For more information see the official [cloud init docs](https://cloudinit.readthedocs.io/en/latest/topics/examples.html).
```

2022-11-25 13:52 UTC, cbosdo commented on salt/virthost/cloudinit/user-data
> +- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOSLK0kJAulwO9Qwm/DVKLsGzv8Fh+ZcGe5x5d+VzO4/+xKnxjOPvGVngm9Hki8N436bCCvIRqwzstDUyJnTHhEe3qzsl02QGqIIfVjzK3BEp4sA8XcmByBy3pxqbTjAjrW8a+n43DBRMx4J86LgywX3fFt8ceE
Is it OK to hard-code this SSH key here? I believe this should be replaced by a grain value

2022-11-25 13:52 UTC, cbosdo commented on salt/virthost/cloudinit/user-data
> +   master: {{grains['server']}}
when was this state executed? during the sumaform process or after registering the virtual host to the server?

2022-11-25 13:52 UTC, cbosdo commented on salt/virthost/cloudinit/user-data
> +   domain-name=tf.local
This is configurable in sumaform. There surely is a grain for that

2022-11-25 13:52 UTC, cbosdo commented on salt/virthost/cloudinit/user-data
> +   sles-salt-migration.tf.local
Strange to see a hard-coded host name here... I think this should be in a grain as this could change depending on the sumaform config. For instance I don't use `tf.local` as domain and the CI probably doesn't either.

2022-11-25 13:52 UTC, cbosdo commented on salt/virthost/cloudinit/user-data
> +   master: {{grains['server']}}
Why are you having all that logic into the cloud init? Smells bad to me 🙊 Couldn't this be done in the testsuite itself? Like Ricardo mentioned earlier I would keep cloud init generic enough to be reusable by other tests

2022-11-25 13:52 UTC, cbosdo commented on salt/virthost/init.sls
> +    - name: mkisofs -o /var/testsuite-data/cloudinit-disk.iso -volid cidata -joliet -rock /root/cloudinit
Using `/root` for this is probably not a super good idea... but should work

2022-11-25 16:15 UTC, nodeg commented on salt/virthost/cloudinit/user-data
> +   master: {{grains['server']}}
This gets executed during the sumaform process.

2022-11-28 08:04 UTC, nodeg commented on salt/virthost/init.sls
> +    - name: mkisofs -o /var/testsuite-data/cloudinit-disk.iso -volid cidata -joliet -rock /root/cloudinit
Fixed.

2022-11-28 09:23 UTC, nodeg commented on salt/virthost/cloudinit/user-data
> +- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOSLK0kJAulwO9Qwm/DVKLsGzv8Fh+ZcGe5x5d+VzO4/+xKnxjOPvGVngm9Hki8N436bCCvIRqwzstDUyJnTHhEe3qzsl02QGqIIfVjzK3BEp4sA8XcmByBy3pxqbTjAjrW8a+n43DBRMx4J86LgywX3fFt8ceE
The [example](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#including-users-and-groups) in the cloud init docs does the same. Nevertheless I can have a look how to replace that.
There is e.g. `salt.states.file.append` but I cannot specify a location inside the file where I want to append things which is important in my case.

2022-11-28 10:25 UTC, nodeg commented
Most of the logic has to be in the cloud init config so when the test suite sets up the nested VM we should have

- a hostname/FQDN
- correct configuration for Avahi, Salt, DNS, etc.

otherwise the VM cannot be seen/onboarded.

I mean I can move that from the cloud init configs to a Salt state to make it configurable via the sumaform configuration but it has to be set up before we ran the test suite.

2022-11-28 14:08 UTC, nodeg commented
Ok, I moved all the logic into the Salt state file for the `virthost`. The replacement of the grains I am querying does also work.

2022-11-29 13:45 UTC, nodeg commented
I adjusted the variables and tested a local sumaform deployment.

I furthermore took a look at `susemanger-ci`. The minimal adjustments for e.g. [4.2](https://github.com/SUSE/susemanager-ci/blob/a84c9b240471e1913f28bfefdcd648b513a59ec3/terracumber_config/tf_files/SUSEManager-4.2-PRV.tf#L192-L193) would be:


**terracumber_config/tf_files/SUSEManager-4.2-PRV.tf**:
```diff
    kvm-host = {
      image = "sles15sp3o"
      additional_grains = {
-        hvm_disk_image = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2"
-        hvm_disk_image_hash = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256"
+        hvm_disk_image = {
+         leap = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2"
+         sles = "https://download.suse.de/install/SLE-15-SP4-Minimal-GM/SLES15-SP4-Minimal-VM.x86_64-OpenStack-Cloud-GM.qcow2"
+        }
+        hvm_disk_image_hash = {
+         leap = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256"
+         sles = "1215677036ea32bf2a8d99770b28cc0e76956def0c14d7a8d30f745ec1f0438c"
+        }
      }
```
Would this be enough and is this the correct way to do it @cbosdo?

The other 2 variables I introduced to the virthost is `hvm_disk_image_name` and `hvm_disk_image_hostname` which do have [default values](https://github.com/uyuni-project/sumaform/pull/1197/files#diff-1a1c4bf64e79a8f4155214c532765cfe62ffcd67e8e3b5a4da7df0bf157944f0) specified, so FMPOV they do not have to be explicitly specified in the `susemanager-ci` terraform files.

```hcl
variable "hvm_disk_image_name" {
  description = "Name of the HVM disk images used as key in other variables"
  type = map(string)
  default = {
    leap = "leap"
    sles = "sles"
  }
}

variable "hvm_disk_image_hostname" {
  description = "Hostname of the HVM disk images"
  type = map(string)
  default = {
    leap = "leap153"
    sles = "sles-salt-migration"
  }
}
```

2022-11-29 16:44 UTC, cbosdo commented
> I adjusted the variables and tested a local sumaform deployment.
> 
> I furthermore took a look at `susemanger-ci`. The minimal adjustments for e.g. [4.2](https://github.com/SUSE/susemanager-ci/blob/a84c9b240471e1913f28bfefdcd648b513a59ec3/terracumber_config/tf_files/SUSEManager-4.2-PRV.tf#L192-L193) would be:
> 
> **terracumber_config/tf_files/SUSEManager-4.2-PRV.tf**:
> 
> ```diff
>     kvm-host = {
>       image = "sles15sp3o"
>       additional_grains = {
> -        hvm_disk_image = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2"
> -        hvm_disk_image_hash = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256"
> +        hvm_disk_image = {
> +         leap = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2"
> +         sles = "https://download.suse.de/install/SLE-15-SP4-Minimal-GM/SLES15-SP4-Minimal-VM.x86_64-OpenStack-Cloud-GM.qcow2"
> +        }
> +        hvm_disk_image_hash = {
> +         leap = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256"
> +         sles = "1215677036ea32bf2a8d99770b28cc0e76956def0c14d7a8d30f745ec1f0438c"
> +        }
>       }
> ```
> 
> Would this be enough and is this the correct way to do it @cbosdo?

Seems good to me. I'm not an HCL expert though 😉 

> The other 2 variables I introduced to the virthost is `hvm_disk_image_name` and `hvm_disk_image_hostname` which do have [default values](https://github.com/uyuni-project/sumaform/pull/1197/files#diff-1a1c4bf64e79a8f4155214c532765cfe62ffcd67e8e3b5a4da7df0bf157944f0) specified, so FMPOV they do not have to be explicitly specified in the `susemanager-ci` [terraform files](https://github.com/SUSE/susemanager-ci/pull/709).
> 
> ```terraform
> variable "hvm_disk_image_name" {
>   description = "Name of the HVM disk images used as key in other variables"
>   type = map(string)
>   default = {
>     leap = "leap"
>     sles = "sles"
>   }
> }

That one looks funny... Can't it be simplified?

> variable "hvm_disk_image_hostname" {
>   description = "Hostname of the HVM disk images"
>   type = map(string)
>   default = {
>     leap = "leap153"
>     sles = "sles-salt-migration"
>   }
> }
> ```

OK

2022-11-30 10:05 UTC, nodeg commented
Thank you for the comments @cbosdo. Do you have a recommendation for a simplification?

2022-11-30 13:43 UTC, nodeg commented
I found one more issue while testing this manually.

```bash
sles-salt-migration:~ # cat /etc/salt/minion
master: sumaform-pxy.tf.local
server_id_use_crc: adler32
enable_legacy_startup_events: False
enable_fqdns_grains: False
```
The `master` is set to the proxy and not the server although I use the following:

```salt
        - content: |
           master: {{ grains.get('server') }}
           server_id_use_crc: adler32
           enable_legacy_startup_events: False
           enable_fqdns_grains: False
          path: /etc/salt/minion
```
When querying this grain on the virthost Minion the server grain is indeed set to the proxy. 

```bash
sumaform-min-kvm:/var/testsuite-data # salt-call --local grains.item server
local:
    ----------
    server:
        sumaform-pxy.tf.local
```

Is this intentional?

2022-12-05 12:54 UTC, cbosdo commented
> Thank you for the comments @cbosdo. Do you have a recommendation for a simplification?

Can't you just suppose and document the variables are consistent across variables? or even document what are the expected values and where it should match?

2022-12-05 12:55 UTC, cbosdo commented
> Is this intentional? It does work to onboard the Minion, though. Just asking.

When the proxy is configured every thing is set to go through it in the testsuite. So I think this is intentional

2022-12-07 09:16 UTC, Bischoff reviewed
see nitpicks

2022-12-07 09:16 UTC, Bischoff commented on README_ADVANCED.md
> +The openSUSE Leap template (`leap`) disk image is `opensuse153o` used by sumaform, the SLES template (`sles`) is a
Make it clear when we use the leap one and when we use the SLES one ?

2022-12-07 09:16 UTC, Bischoff commented on README_ADVANCED.md
> +The openSUSE Leap template (`leap`) disk image is `opensuse153o` used by sumaform, the SLES template (`sles`) is a
is the above wrong?
```
SUSE/susemanager-ci/terracumber_config/tf_files> grep hvm SUSEManager-*-PRV.tf 
SUSEManager-4.2-PRV.tf:        hvm_disk_image =
 "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2"
SUSEManager-4.2-PRV.tf:        hvm_disk_image_hash =
 "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256"
SUSEManager-4.3-PRV.tf:        hvm_disk_image =
 "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.x86_64-OpenStack-Cloud.qcow2"
SUSEManager-4.3-PRV.tf:        hvm_disk_image_hash =
 "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256"
```
it looks like we have both Leap 15.3 and 15.4

(btw, is there a reason for keeping 15.3?)

2022-12-07 09:16 UTC, Bischoff commented on README_TESTING.md
>              xen_disk_image = "..."
does it make sense to have xen data on a kvm host?

2022-12-07 09:16 UTC, Bischoff commented on README_TESTING.md
> +            hvm_disk_image = {
does it make sense to have kvm data on a xen host?

2022-12-07 09:30 UTC, cbosdo commented on README_TESTING.md
>              xen_disk_image = "..."
the virthost module was used for both KVM and Xen. I believe we can now remove all Xen support from sumaform, but that could be done in a separate PR

2022-12-07 10:33 UTC, nodeg commented on README_ADVANCED.md
> +The openSUSE Leap template (`leap`) disk image is `opensuse153o` used by sumaform, the SLES template (`sles`) is a
I do not want to add more to this PR. Updating Leap to 15.4 can be done in a separate PR.

I am not sure if I should add more information about our test suite to the general sumaform docs here. I can explain it to you here if that is enough:

- Leap is used for the general KVM test in our test suite
- SLES is used for the Salt bundle migration test

2022-12-07 11:03 UTC, Bischoff approved these changes
we might need to do other things in other PRs:
* remove xen
* move from leap 15.3 to 15.4

approving

2022-12-07 11:03 UTC, Bischoff commented on README_ADVANCED.md
> +The openSUSE Leap template (`leap`) disk image is `opensuse153o` used by sumaform, the SLES template (`sles`) is a
1) ok   2) ok, fair enough

2022-12-07 11:56 UTC, nodeg commented
For XEN I already created a card for hexagon. Updating Leap ist one thing I will do after the Salt bundle test PRs got merged.

2022-12-08 08:22 UTC, nodeg commented
Ok, so `map(map(string))` does work:

```salt
sumaform-min-kvm:~ # salt-call --local grains.item hvm_disk_image
local:
    ----------
    hvm_disk_image:
        ----------
        leap:
            ----------
            hash:
                https://download.opensuse.org/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256
            hostname:
                leap153
            image:
                https://download.opensuse.org/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2
            name:
                leap
        sles:
            ----------
            hash:
                http://minima-mirror.mgr.suse.de/install/SLE-15-SP4-Minimal-GM/SLES15-SP4-Minimal-VM.x86_64-OpenStack-Cloud-GM.qcow2.sha256
            hostname:
                sles-salt-migration
            image:
                https://download.suse.de/install/SLE-15-SP4-Minimal-GM/SLES15-SP4-Minimal-VM.x86_64-OpenStack-Cloud-GM.qcow2
            name:
                sles
```

2022-12-08 13:15 UTC, nodeg commented
I am currently testing this locally and will then request another review from you @cbosdo :wink:

2022-12-09 10:13 UTC, nodeg commented
Ok, sumaform is deploying successfully.

2022-12-09 13:33 UTC, nodeg commented
Apparently it did not work that well. I did a deployment where this branched was checked out. My `main.tf` for the virthost looks like the following:

```hcl
    kvm-host = {
      hvm_disk_image = {
        leap = {
          name = "leap"
          hostname = "leap-salt-migration"
          image = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.x86_64-OpenStack-Cloud.qcow2"
          hash = "http://minima-mirror.mgr.prv.suse.net/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256"
        }
        sles = {
          name = "sles"
          hostname = "sles-salt-migration"
          image = "http://minima-mirror.mgr.prv.suse.net/install/SLE-15-SP4-Minimal-GM/SLES15-SP4-Minimal-VM.x86_64-OpenStack-Cloud-GM.qcow2"
          hash = "http://minima-mirror.mgr.prv.suse.net/install/SLE-15-SP4-Minimal-GM/SLES15-SP4-Minimal-VM.x86_64-OpenStack-Cloud-GM.qcow2.sha256"
        }
      }
```
but when verifying this after the sumaform deployment there was only the default value from sumaform present on the virthost:

```bash
sumaform-min-kvm:~/salt/virthost # salt-call --local grains.item hvm_disk_image
local:
    ----------
    hvm_disk_image:
        ----------
        leap:
            ----------
            hash:
                https://download.opensuse.org/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256
            hostname:
                leap153
            image:
                https://download.opensuse.org/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2
            name:
                leap
sumaform-min-kvm:~/salt/virthost # 
```

2022-12-19 12:38 UTC, cbosdo reviewed
Some more data deduplication is possible

2022-12-19 12:38 UTC, cbosdo commented on salt/virthost/init.sls
> +rezise-{{ salt['grains.get']('hvm_disk_image:' ~ os_type ~ ':name') }}-disk-image-template:
Why don't you use `os_type` directly instead of `salt['grains.get']('hvm_disk_image:' ~ os_type ~ ':name')` since those are basically the same in your values?

I would drop the `name` property and just use the map key instead: one less duplicate data

2022-12-19 12:38 UTC, cbosdo commented on modules/virthost/variables.tf
> +      name = "leap"
You probably can get rid of the `name` value and use the item's key instead.

2022-12-19 12:38 UTC, cbosdo commented on README_TESTING.md
> +          name = "..."
`name` should be removed here too

2022-12-19 13:09 UTC, vandabarata approved these changes
lgtm, I'd just do the changes suggested by Cedric to avoid duplication

2022-12-19 13:53 UTC, nodeg commented on modules/virthost/variables.tf
> +      name = "leap"
Fixed.

2022-12-19 13:53 UTC, nodeg commented on README_TESTING.md
> +          name = "..."
Fixed.

2022-12-19 14:06 UTC, nodeg commented
Rebased and adjusted the commits.

2022-12-19 15:03 UTC, cbosdo approved these changes
Left a couple of comments that could be addressed later

2022-12-19 15:03 UTC, cbosdo commented on README_ADVANCED.md
> +If the values inside the `hvm_disk_image` map are set to an empty string, no image will be copied to `/var/testsuite-data/`.
Empty map... is the testsuite automatically disabling the virtualization features if the image isn't there? I expect there could be issues with this..

2022-12-19 15:03 UTC, cbosdo commented on salt/virthost/init.sls
> +{% for os_type in grains.get('hvm_disk_image') %}
How comes this is not merged with the previous loop since those are looping on the same things?

2022-12-19 15:08 UTC, nodeg commented on README_ADVANCED.md
> +If the values inside the `hvm_disk_image` map are set to an empty string, no image will be copied to `/var/testsuite-data/`.
No, the feature is not disabled but we raise a warning and abort the current scenario. The sentence above is to inform the user that if the values are empty, we do not have any images in the mentioned folder above.

2022-12-19 15:09 UTC, nodeg commented on salt/virthost/init.sls
> +{% for os_type in grains.get('hvm_disk_image') %}
Nice catch. Before addressing your other suggestion regarding the name variable above it was not possible to use one loop. After changing the code, this for loop can be "merged" with the other. Thank you.

2022-12-19 15:11 UTC, nodeg commented on salt/virthost/init.sls
> +{% for os_type in grains.get('hvm_disk_image') %}
I amended the changes.

2022-12-20 12:50 UTC, merged