Remove some unsupported clients
uyuni-project/sumaform pull request #1261
Opened 2023-03-01 12:00 UTC by Bischoff

## What does this PR change?

Remove CentOS 6, CentOS 8, CentOS 9, and Debian 9

2023-03-01 13:07 UTC, juliogonzalez reviewed
Some comments.

And I can't tell for sure if this addressing all required changes, as I didn't grep by myself, but I hope you did.

Also remember that Ricardo is not the maintainer anymore, but Naica is. Add them as reviewers.

2023-03-01 13:07 UTC, juliogonzalez commented on backend_modules/libvirt/host/user_data.yaml
> -%{ endif }
I think removing the lines about this one is not right? doesn't this belong to debian10o?

2023-03-01 13:07 UTC, juliogonzalez commented on backend_modules/libvirt/host/user_data.yaml
>  %{ if install_salt_bundle }
Shouldn't you remove this instead? Or maybe I am getting confused by the diff.

2023-03-01 14:08 UTC, Bischoff commented
> > The following repository remains:
> > http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/
> > CentOS8-Uyuni-Client-Tools/CentOS_8/
> > because of the RHEL 8 image case (cloud only).
> 
> Wrong repo. RHEL8 image image must use EL8 client tools. The repo you pasted stopped getting updates when CentOS8 became EoL.

Thanks, I kind of suspected it. I will fix that. Ping @maximenoel8 .

2023-03-01 14:10 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
> -%{ endif }
This is an artifact of the diff. Since the lines are almost identical for debian 9 and debian 10, diff is a bit puzzled about which lines I really removed.

Add more lines above and before and you'll see the change is correct.

2023-03-01 14:11 UTC, Bischoff commented
> Some comments.

Thanks a lot.

> And I can't tell for sure if this addressing all required changes, as I didn't grep by myself, but I hope you did.

grep is my best firend :smile: .

> Also remember that Ricardo is not the maintainer anymore, but Naica is. Add them as reviewers.

Er, how do I add a team as reviewers ?

2023-03-01 14:12 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
>  %{ if install_salt_bundle }
See above.

2023-03-01 14:27 UTC, juliogonzalez commented on backend_modules/libvirt/host/user_data.yaml
> -%{ endif }
ACK, resolving then.

2023-03-01 14:28 UTC, juliogonzalez commented
> Er, how do I add a team as reviewers ?

IIRC @cbbayburt spoke about taking care of it, maybe not the whole squad. Check with him.

2023-03-01 14:33 UTC, juliogonzalez approved these changes
I see you adjusted http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS8-Uyuni-Client-Tools/CentOS_8/ to http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL8-Uyuni-Client-Tools/EL_8/

Make sure you do the same for the `Master` URLs, if they were not fixed already.

Other than that, and assuming all greps are OK, LGTM.

But get a review from the sumaform maintainers as well :-)

2023-03-01 14:40 UTC, Bischoff commented
> I see you adjusted http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS8-Uyuni-Client-Tools/CentOS_8/ to http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL8-Uyuni-Client-Tools/EL_8/
> 
> Make sure you do the same for the `Master` URLs, if they were not fixed already.

I added them now by symmetry. In the first iteration I had only the `Stable:` ones, because it's the only ones used (in AWS and azure backends).

 
> Other than that, and assuming all greps are OK, LGTM.
```
sumaform> grep -Ri CentOS_8 2>/dev/null | grep -v '\.git'
sumaform> grep -Ri CentOS_9 2>/dev/null | grep -v '\.git'
sumaform> grep -Ri centos8 2>/dev/null | grep -v '\.git'
sumaform> grep -Ri centos9 2>/dev/null | grep -v '\.git'
sumaform> grep -Ri centos6 2>/dev/null | grep -v '\.git'
sumaform> grep -Ri debian9 2>/dev/null | grep -v '\.git'
sumaform>
```

> But get a review from the sumaform maintainers as well :-)

Sure. Can is in the loop now.

2023-03-02 09:55 UTC, ktsamis approved these changes

2023-03-02 10:20 UTC, elariekerboull approved these changes
lgtm

2023-03-02 10:25 UTC, nodeg approved these changes

2023-03-02 10:40 UTC, srbarrios requested changes
Let's please not remove CentOS Stream support from Sumaform.
The reason about it:
- SUMA don't support it
- Uyuni users can still use it via spacewalk common channels

2023-03-02 12:05 UTC, srbarrios approved these changes
LGTM

2023-03-02 12:08 UTC, cbbayburt approved these changes

2023-03-02 12:44 UTC, merged