change remote debug tomcat configuration
uyuni-project/sumaform pull request #1276
Opened 2023-03-30 08:17 UTC by mbussolotto

## What does this PR change?

I'm trying to clean up all the tomcat custom configuration in uyuni and sumaform. Currently we have configuration in:
- `/etc/sysconfig/tomcat`
- `/etc/tomcat.conf`
and apply them requires parsing the content with some regex.
This change is aligned with the ones that I'm having for `uyuni`, wher each different configuration is in a different file in `/etc/tomcat/conf.d/*conf`

2023-03-31 09:27 UTC, cbosdo requested changes
Idempotency issue

2023-03-31 09:27 UTC, cbosdo commented on salt/server/tomcat.sls
> +  file.append:
This only works for the first run. You should use a `file.replace` with `append_if_not_found: True` instead.

2023-04-05 16:12 UTC, mbussolotto commented on salt/server/tomcat.sls
> +  file.append:
it should be better now

2023-04-06 07:54 UTC, cbosdo reviewed
Using `file.touch` would be more elegant than managing an empty file... and it avoids resetting the file content if no change is required.

2023-04-06 07:54 UTC, cbosdo commented on salt/server/tomcat.sls
> +  file.managed:
You can use https://docs.saltproject.io/en/latest/ref/states/all/salt.states.file.html#salt.states.file.touch here

2023-04-06 09:11 UTC, cbosdo approved these changes

2023-04-06 12:27 UTC, merged

2023-05-12 07:08 UTC, srbarrios commented
Hi there, just for your information, this PR broke one month ago the pipeline that runs the test suite with a JaCoCo agent in place, to collect test coverage.
I did not had time until now to debug the reasons about what that was failing.

We were injecting the config from here:
https://github.com/SUSE/susemanager-ci/blob/master/terracumber_config/config_files/etc_sysconfig_tomcat

I'm gonna fix it now by creating another file in /etc/tomcat/conf.d/ at main.tf level, as I need results asap.
But we might want to consider moving JaCoCo enablement for the testsuite at sumaform level, to avoid the unalignment.

2023-05-12 07:15 UTC, mbussolotto commented
Thanks Oscar, I wasn't aware of that. 
 > But we might want to consider https://github.com/uyuni-project/sumaform/issues/1305, to avoid the unalignment.

+1