Clean RH like minion repository
uyuni-project/sumaform pull request #1294
Opened 2023-05-01 04:34 UTC by maximenoel8

## What does this PR change?

venv-slat is not available in

2023-05-02 12:08 UTC, meaksh requested changes

2023-05-02 12:08 UTC, meaksh commented on salt/repos/default.sls
> -    {% endif %}
IIUC I think we should not remove this block, as we would have problems then with RES7 when using a mirror. Maybe we want to refactor this instead.

From what I can see, the problem is on RES7 only, as even if https://download.suse.de/ibs/SUSE/Updates/RES/7-CLIENT-TOOLS/x86_64/update/x86_64/ exists, the "minima" mirrors we use in our CIs (which synchronize these channels from SCC), are still getting this other "$RCE" path synced:

```
minima-mirror:/srv/mirror # find .| grep RES | grep repomd.xml$
./repo/$RCE/RES7-SUSE-Manager-Tools/x86_64/repodata/repomd.xml
./repo/$RCE/RES7-SUSE-Manager-Tools-Beta/x86_64/repodata/repomd.xml
./SUSE/Products/RES/8-CLIENT-TOOLS/x86_64/product/repodata/repomd.xml
./SUSE/Updates/RES-CB/8/x86_64/update/repodata/repomd.xml
./SUSE/Updates/RES-AS/8/x86_64/update/repodata/repomd.xml
./SUSE/Updates/RES/8-CLIENT-TOOLS/x86_64/update/repodata/repomd.xml
./SUSE/Updates/RES/8/x86_64/update/repodata/repomd.xml
```

I have no idea why we are getting that one $RCE repo from SCC instead of the other ones, but with the current changes proposed on this PR, the RES7 instances would have errors as configured repositories won't be existing when using "minima mirrors".

2023-05-02 13:28 UTC, srbarrios commented on salt/repos/default.sls
> -    {% endif %}
If the issue is only in the mirror, and it's about a different path.
I propose to create a symbolic link that points to that /repo/$RCE folder and that would solve the problem (hacky but effective, I guess)

2023-06-08 14:24 UTC, srbarrios approved these changes

2023-06-08 22:53 UTC, closed without merging