Make "cloud-init" to setup a repo that provides "venv-salt-minion" package
uyuni-project/sumaform pull request #1312
Opened 2023-05-24 13:00 UTC by meaksh

## What does this PR change?

This PR makes `cloud-init` to configure corresponding Client Tools channels in SLE/openSUSE images, in order to have a configured repository which is able to provide `venv-salt-minion` package to run the deployment.

This should fix the current issue we see on our testsuites deployments: https://github.com/SUSE/spacewalk/issues/21545

I've tested deployments of SLE12SP4 and SLE15SP4/SP3 instances with these changes and they were successful.

2023-05-24 13:33 UTC, cbbayburt requested changes

2023-05-24 13:33 UTC, cbbayburt commented on backend_modules/libvirt/host/user_data.yaml
> +      baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org"}/repositories/systemsmanagement:/Uyuni:/Stable:/SLE12-Uyuni-Client-Tools/SLE_12/
I think it would be more accurate to use SUSE Manager Tools repos with SLES images (also with the others below).
```suggestion
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/Devel:/Galaxy:/Manager:/4.3:/SLE12-SUSE-Manager-Tools/SLE_12/
```

2023-05-24 15:09 UTC, cbbayburt approved these changes

2023-05-25 07:44 UTC, agraul approved these changes
As long as we have something after the "update packages" state, which updates Salt, I think the errors we have seen can still happen with clients that include Salt in the image. Not when we tell sumaform to install the bundle, that part probably works now (as long as there are no network hickups when cloud-init installs the bundle).

We can merge this now, but that shouldn't keep us from fixing the other parts that contribute to the problem.

2023-05-25 08:26 UTC, merged