Additional disk for /var/lib/pgsql partition custom size
uyuni-project/sumaform pull request #1454
Opened 2023-12-29 12:49 UTC by srbarrios

## What does this PR change?

**add description**

2023-12-31 08:03 UTC, mcalmer requested changes

2023-12-31 08:03 UTC, mcalmer commented on salt/server/additional_disk.sls
> +    - makedirs: True
This dir requires special ownership and permissions. If you create it, you should also adapt this

2024-01-02 08:28 UTC, srbarrios commented on salt/server/additional_disk.sls
> +    - makedirs: True
Thanks for the remark, I will take a look.
(For now, I did not even tried to deploy using this code)

2024-01-02 08:44 UTC, srbarrios commented on salt/server/additional_disk.sls
> +    - makedirs: True
```
chmod 750 /var/lib/pgsql
chown postgres:postgres /var/lib/pgsql
```

2024-01-02 09:06 UTC, srbarrios commented on salt/server/additional_disk.sls
> +    - makedirs: True
Ok, it seems I will not need it here.
It seems that it's adjusted later on, when we install the packages for both suse manager and postgres.

As a fact, we also don't set up a user and group for the partition `/var/spacewalk` but it's still correct at the end of the deployment.

```
drwxr-xr-x  6 wwwrun root 4096 nov 24 16:23 spacewalk
```

2024-01-02 10:08 UTC, mcalmer commented on salt/server/additional_disk.sls
> +    - makedirs: True
ok

2024-01-02 10:09 UTC, mcalmer approved these changes

2024-01-02 17:26 UTC, srbarrios commented on salt/server/additional_disk.sls
> +    - makedirs: True
Well, at the end, it seems it was necessary 🤷🏼‍♂️

2024-01-02 18:46 UTC, Bischoff approved these changes

2024-01-02 20:10 UTC, maximenoel8 requested changes

2024-01-02 20:10 UTC, maximenoel8 commented on salt/server/additional_disk.sls
> +{% set partition_name = '/dev/vdc1' %}
I'm not sure it's  a good idea to have hard written the partition_name. It will not be compatible with cloud deployment. 
Why not using the same method than data disk ? grains['data_disk_device'] ?

2024-01-03 11:14 UTC, srbarrios commented on salt/server/additional_disk.sls
> +{% set partition_name = '/dev/vdc1' %}
Because that will require a bigger refactor, I choose this faster approach.

data_disk_device is not at server module level but at a lower level, so it makes things harder, we might want to convert data_disk_device into an array and rename it as data_disk_devices, otherwise it might not make sense depending the module.

I agree we can address it, but I would do it in another PR, so we have this ready today to make stable our CI again, currently, once we try to backup the database it fails and doesn't recover.

2024-01-03 15:07 UTC, srbarrios commented on salt/server/additional_disk.sls
> +{% set partition_name = '/dev/vdc1' %}
Honestly, I'm not super happy with the naming... but just for the sake of supporting cloud setups... I made the easiest adjustments I could to have another data_disk_device, I called it second_data_disk_device to keep it agnostic as this is setup at host module.

2024-01-04 08:32 UTC, merged