Add disk container symlink
uyuni-project/sumaform pull request #1480
Opened 2024-01-26 00:37 UTC by maximenoel8

## What does this PR change?
Use symbolic link to add extra disk to container

2024-01-26 08:50 UTC, srbarrios commented on modules/server_containerized/main.tf
> +    "head"           = "slemicro55-ign"
True, but we can't change this directly, we first need to align with another PR we are working on.
Let's keep this change out of this PR please.

2024-01-26 08:52 UTC, srbarrios approved these changes
Approving, but please read by comment about head image before merging.

2024-01-26 08:53 UTC, srbarrios requested changes
It seems something is wrong, check the GH checks:
https://github.com/uyuni-project/sumaform/actions/runs/7663252752/job/20885774161?pr=1480#step:9:134

2024-01-26 09:15 UTC, cbosdo commented on modules/server_containerized/main.tf
> +    "head"           = "slemicro55-ign"
I'll be fixing this in my PR for sure

2024-01-26 09:18 UTC, cbosdo reviewed
I still don't get why you need those two disks and not just one, but the PR looks good to me otherwise.

2024-01-26 11:44 UTC, rjmateus approved these changes
looks good.

2024-01-31 08:04 UTC, maximenoel8 commented
@srbarrios Could you review this PR and see if the changes are correct please

2024-01-31 14:57 UTC, nodeg reviewed
Maxime, you should also take a look at the test and adjust the testing template by adding the 2 missing variables.

```bash
╷
│ Error: Reference to undeclared input variable
│ 
│   on modules/server_containerized/main.tf line 35, in module "server_containerized":
│   35:   additional_disk_size          = var.additional_disk_size
│ 
│ An input variable with the name "additional_disk_size" has not been
│ declared. This variable can be declared with a variable
│ "additional_disk_size" {} block.
╵
╷
│ Error: Reference to undeclared input variable
│ 
│   on modules/server_containerized/main.tf line 36, in module "server_containerized":
│   36:   second_additional_disk_size   = var.second_additional_disk_size
│ 
│ An input variable with the name "second_additional_disk_size" has not been
│ declared. This variable can be declared with a variable
│ "second_additional_disk_size" {} block.
```

2024-02-01 02:38 UTC, maximenoel8 commented
Thanks, probably a rebase change ...

2024-02-01 08:24 UTC, srbarrios approved these changes

2024-02-01 08:28 UTC, merged