Enable SCC access logging by default
uyuni-project/sumaform pull request #1519
Opened 2024-02-28 10:42 UTC by mtravitzky

This will enable the [SCC access logger](https://github.com/uyuni-project/uyuni/pull/7878) by default in testing deployments on both, server and server_containerized. This additional logging is needed for additional tests against SCC flooding in the testsuite.

2024-02-28 11:11 UTC, srbarrios commented on modules/server/variables.tf
> +  description = "enable logging for SCC access through taskomatic and tomcat"
Actually... if you compare with all the other variable descriptions...

2024-02-28 11:12 UTC, srbarrios commented on modules/server_containerized/variables.tf
> +  default     = true
🚨 Let's please have this disabled by default.
And we will enable it through our different main.tf files, in the environments we decide we want this.

2024-02-28 11:15 UTC, srbarrios commented on salt/server/taskomatic.sls
> +  - server
Are you sure we want to include server? Why this can't go in server.rhn?
If so, do we want this wrapped like:
```
{% if grains.get('scc_access_logging') %}
  - server
{% endif %}
```

2024-02-28 11:17 UTC, srbarrios commented on salt/server/taskomatic.sls
> +    - content: '        <Logger name="com.suse.scc.client.SCCWebClient" level="info" />'
I'm not fully sure, but I would guess by the above `hibernate_debug_log` state, that we need an additional `</Logger>` in this injected line.

2024-02-28 11:20 UTC, srbarrios commented on salt/server_containerized/taskomatic.sls
> +  - server_containerized
I don't get why exactly we need to include this.

2024-02-28 11:20 UTC, srbarrios commented on salt/server_containerized/tomcat.sls
> +  - server_containerized
I don't get why exactly we need to include this.

2024-02-28 11:21 UTC, srbarrios commented on salt/server_containerized/taskomatic.sls
> +      - sls: server_containerized
What we exactly require?

2024-02-28 11:22 UTC, srbarrios requested changes
Please, review my comments.
The most important request is to don't enable this by default.

2024-02-28 11:23 UTC, ktsamis approved these changes
Looks good

2024-02-28 11:25 UTC, ktsamis requested changes
Nope sorry we shouldn't enable by default for all servers. Oscar's review is more thorough

2024-02-28 11:27 UTC, srbarrios commented on salt/server/tomcat.sls
> +    set tomcat_log4j2_xml_path = "/srv/tomcat/webapps/rhn/WEB-INF/classes/log4j2.xml"
That should be that way right?
```suggestion
{% set tomcat_log4j2_xml_path = "/srv/tomcat/webapps/rhn/WEB-INF/classes/log4j2.xml" %}
```

2024-02-28 11:28 UTC, srbarrios commented on salt/server/tomcat.sls
> +  {% set tomcat_log4j2_xml_path = "/usr/share/susemanager/www/tomcat/webapps/rhn/WEB-INF/classes/log4j2.xml" %}
We don't indent Jinja2 code.

2024-02-28 11:35 UTC, mtravitzky commented on modules/server/variables.tf
> +  description = "enable logging for SCC access through taskomatic and tomcat"
This is also the reason why I used a lowercase e

2024-02-28 11:36 UTC, srbarrios commented on salt/server_containerized/taskomatic.sls
> +    - name: /usr/share/rhn/classes/log4j2.xml
This file will for sure don't exist on that machine.
This file will be found inside the podman container of the server.
In order to have this working, you need to either point to the volume path, either you need to use mgrctl exec -ti bash, to navigating and acts on the server container.

2024-02-28 11:36 UTC, srbarrios commented on salt/server_containerized/tomcat.sls
> +    - name: /usr/share/susemanager/www/tomcat/webapps/rhn/WEB-INF/classes/log4j2.xml
This file will for sure don't exist on that machine.
This file will be found inside the podman container of the server.
In order to have this working, you need to either point to the volume path, either you need to use mgrctl exec -ti bash, to navigating and acts on the server container.

2024-02-28 11:44 UTC, mtravitzky commented on salt/server_containerized/tomcat.sls
> +  - server_containerized
I mimicked the "server"-requirement from /server/tomcat.sls, which also doesn't seem necessary at first but is still there

2024-02-28 11:49 UTC, mtravitzky commented on modules/server_containerized/variables.tf
> +  default     = true
In this case, I need to know these environments beforehand to also check for their tags in the testsuite cucumber code

2024-02-28 12:02 UTC, srbarrios commented on salt/server_containerized/tomcat.sls
> +  - server_containerized
In the section you mention, we need `server.rhn` https://github.com/uyuni-project/sumaform/blob/master/salt/server/rhn.sls because we act on rhn.conf file, and we want to run first some salt states on it.

For instance:

```
# catch-all to ensure we always have at least one state covering /etc/rhn/rhn.conf
rhn_conf_present:
  file.touch:
    - name: /etc/rhn/rhn.conf
```

2024-02-28 12:08 UTC, mtravitzky commented on salt/server/taskomatic.sls
> +    - content: '        <Logger name="com.suse.scc.client.SCCWebClient" level="info" />'
Actually, we don't. This is redundant due to using the <tag /> syntax. It's only needed in some other places, where an Appender is specified within a <Logger></Logger> tag.

2024-02-28 13:24 UTC, srbarrios commented on modules/server/variables.tf
> +  default     = true
```suggestion
  default     = false
```

2024-02-28 13:35 UTC, mtravitzky commented on salt/server/tomcat.sls
> +  {% if __salt__["file.exists"]("/srv/tomcat/webapps/rhn/WEB-INF/classes/log4j2.xml") %}
I did it this way just to ensure the variable actually exists

2024-02-28 14:08 UTC, Bischoff commented on modules/server/variables.tf
> +  description = "enable logging for SCC access through taskomatic and tomcat"
I just compared with next one: "Swap".

2024-02-28 14:08 UTC, Bischoff approved these changes

2024-02-28 14:41 UTC, srbarrios commented on salt/server/tomcat.sls
> +{% if grains.get('java_debugging') or grains.get('java_salt_debugging') %}
Let's follow here the same strategy you made in taskomatic.sls ?

2024-02-28 14:42 UTC, srbarrios commented on salt/server/tomcat.sls
> +  {% set tomcat_log4j2_xml_path = "/srv/tomcat/webapps/rhn/WEB-INF/classes/log4j2.xml" %}
Please remove the indent in the set lines.

2024-02-28 14:42 UTC, srbarrios commented on salt/server/taskomatic.sls
> +      - sls: server
```suggestion
      - sls: server.rhn
```

2024-02-28 14:44 UTC, srbarrios commented on salt/server/tomcat.sls
> +{% if grains.get('java_debugging') or grains.get('java_salt_debugging') %}
```suggestion
{% if grains.get('java_debugging') or grains.get('java_salt_debugging') or grains.get('scc_access_logging') %}
include:
  - server.rhn
{% endif %}
```

2024-02-28 14:45 UTC, srbarrios commented on salt/server/tomcat.sls
> +      - sls: server
```suggestion
      - sls: server.rhn
```

2024-02-28 14:49 UTC, mtravitzky commented on modules/server/variables.tf
> +  description = "enable logging for SCC access through taskomatic and tomcat"
Changed to a capital E

2024-02-28 14:55 UTC, srbarrios approved these changes
Thank you so much. LGTM.

2024-02-28 15:01 UTC, NamelessOne91 approved these changes
LGTM - Thanks Marc !

2024-02-28 15:46 UTC, agraul commented on salt/server/tomcat.sls
> +      - sls: server
Why? This state doesn't need anything that `server.rhn` provides (over `server`)

2024-02-28 15:48 UTC, agraul commented on salt/server/tomcat.sls
> +{% if grains.get('java_debugging') or grains.get('java_salt_debugging') %}
That's not the whole folder, at least not directly (it's `server.sls` / `server/init.sls`) and it's good practice to specify what is mentioned with `requires`. In sumaform in particular, it does not matter as much since the entry point is always `server/init.sls` (which includes `server.tomcat`)

2024-02-29 09:59 UTC, agraul approved these changes

2024-02-29 12:14 UTC, nodeg approved these changes
LGTM. Thank you, Marc!

2024-03-01 15:50 UTC, Bischoff approved these changes
LGTM

2024-03-04 10:32 UTC, srbarrios commented on salt/server/tomcat.sls
> +    - name: {{tomcat_log4j2_xml_path}}
I'm not 100% sure, but I think this must be written like that:
```suggestion
    - name: {{ tomcat_log4j2_xml_path }}
```

2024-03-04 10:33 UTC, srbarrios approved these changes

2024-03-04 10:39 UTC, merged

2024-03-04 12:21 UTC, agraul commented on salt/server/tomcat.sls
> +    - name: {{tomcat_log4j2_xml_path}}
JFI, spaces are not required:
```
43-server:~ # cat /srv/salt/foo.sls 
test:
  test.show_notification:
    - text: 1 + 1 = {{1+1}}
43-server:~ # salt 43-alma8* state.apply foo
43-alma8.tf.local:
----------
          ID: test
    Function: test.show_notification
      Result: True
     Comment: 1 + 1 = 2
     Started: 13:21:11.584229
    Duration: 0.506 ms
     Changes:   

Summary for 43-alma8.tf.local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.506 ms

2024-03-04 12:39 UTC, nodeg commented on salt/server/tomcat.sls
> +    - name: {{tomcat_log4j2_xml_path}}
I think this is only a matter of taste, reading improvement and linting. Thank you for doing this quick test, Alex!