Enable salt_env module to use openSUSE Tumbleweed
uyuni-project/sumaform pull request #1589
Opened 2024-05-21 08:36 UTC by ycedres

## What does this PR change?

The goal is to be able to run Salt Shaker tests in openSUSE Tumbleweed (for the classic Salt package).

2024-05-21 09:18 UTC, meaksh requested changes

2024-05-21 09:18 UTC, meaksh commented on backend_modules/libvirt/base/main.tf
> +    tumbleweedo               = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.opensuse.org"}/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2"
Nitpick: let have same alignment here:

```suggestion
    tumbleweedo              = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.opensuse.org"}/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2"
```

2024-05-21 09:18 UTC, meaksh commented on backend_modules/libvirt/host/user_data.yaml
> +  - zypper --non-interactive install avahi avahi-lang
Question: why not putting `avahi` and `avahi-lang` in the `packages` section instead of manually calling Zypper here?

2024-05-21 09:18 UTC, meaksh commented on salt/repos/default.sls
> +
Is this really needed?

```suggestion
```

2024-05-21 09:18 UTC, meaksh commented on salt/salt_testenv/init.sls
> -{% if grains['osfullname'] == 'SLES' and grains['osrelease_info'][1] >= 3 %}
You cannot remove the `osfullname` == 'SLES'` check here, as that would affect then to `SL-Micro` too.

2024-05-21 11:17 UTC, ycedres commented on salt/repos/default.sls
> +
Sorry, that slipped in.

2024-05-21 11:17 UTC, ycedres commented on backend_modules/libvirt/host/user_data.yaml
> +  - zypper --non-interactive install avahi avahi-lang
You're right, I moved it to the `packages` list.

2024-05-21 11:34 UTC, meaksh commented on salt/salt_testenv/init.sls
> -{% endif %}
I think moving the `{% endif %}` is not really required, or? I would refactor this somehow and not remove this `{% endif %}` as it is right now.

If you remove it, then next if/else (line ~41) will set `repo_path` to `SLE_15_SP*` for SLMicro.

2024-05-22 08:32 UTC, ycedres commented on salt/salt_testenv/init.sls
> -{% if grains['osfullname'] == 'SLES' and grains['osrelease_info'][1] >= 3 %}
After our conversation yesterday I've refactored it a bit. Now (for the classic Salt installation) I'm using the `os` grain to treat every SUSE based OS. Then I discriminate between SLES, TW and SL-Micro.

2024-05-23 14:46 UTC, meaksh approved these changes

2024-05-24 09:41 UTC, Bischoff requested changes
just nitpicks

2024-05-24 09:41 UTC, Bischoff commented on backend_modules/libvirt/base/main.tf
> +
remove empty line ?

2024-05-24 09:41 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
> +packages: ["salt", "salt-minion", "avahi", "avahi-lang"]
add a comment here about the purpose of using salt-minion instead of venv-salt-minion?

2024-05-24 09:41 UTC, Bischoff commented on backend_modules/null/base/variables.tf
> +  default     = [ "almalinux8o", "almalinux9o", "amazonlinux2o", "centos7o", "libertylinux9o", "opensuse154o", "opensuse155o", "oraclelinux9o", "rocky8o", "rocky9o", "sles12sp4o", "sles12sp5o", "sles
order: tumbleweed after the other opensuses?

2024-05-24 10:59 UTC, Bischoff approved these changes

2024-05-24 11:09 UTC, merged