Fix the salt_testenv module to properly run Salt Shaker tests in Leap
uyuni-project/sumaform pull request #1596
Opened 2024-05-28 09:56 UTC by ycedres

## What does this PR change?

Also fixes missing bits for testing the Salt package built in in `systemsmanagement:saltstack`.

2024-05-28 11:36 UTC, meaksh requested changes

2024-05-28 11:36 UTC, meaksh commented on salt/salt_testenv/init.sls
> +{% elif grains["salt_obs_flavor"] == "saltstack:testing" %}
We do not have this flavor anymore, we removed `saltstack:testing` some time ago

2024-05-28 11:36 UTC, meaksh commented on salt/salt_testenv/init.sls
> +{% elif grains["salt_obs_flavor"] == "saltstack:next}
Same here for `saltstack:next`. We are not using it.

2024-05-28 11:36 UTC, meaksh commented on salt/salt_testenv/init.sls
> +{% if ((grains['osfullname'] == 'SLES' and grains['osrelease_info'][0] == 15) or (grains['osfullname'] == 'Leap')) %}
If we set this, then Leap would configure the repositories that we set for SLE, which is not correct and probably not really needed.

2024-05-29 05:24 UTC, ycedres commented on salt/salt_testenv/init.sls
> +{% elif grains["salt_obs_flavor"] == "saltstack:testing" %}
Now I just check that we install the bundle if we're running the Salt Shaker test suite in an environment different from the `systemsmanagement:saltstack` OBS project.

2024-05-29 09:19 UTC, meaksh approved these changes

2024-05-29 09:22 UTC, merged