Adding a repo to unblock the deployment of SLMicro6.0 with Classic Salt
uyuni-project/sumaform pull request #1609
Opened 2024-06-03 14:01 UTC by srbarrios

## What does this PR change?

Adding a repo to unblock the deployment of SLMicro6.0 with Classic Salt

2024-06-03 15:14 UTC, srbarrios commented
It does not work...
```
... micro/6.0/product/repo/Leap-Micro-6.0-x86_64-Media1/] Valid metadata not found 
```

2024-06-05 08:19 UTC, srbarrios commented on salt/default/sshd.sls
> +{% if grains['os'] == 'SUSE' and not grains['osrelease'] in ['15.6', '6.0'] %}
@meaksh I had to do this... make sense for you?
Otherwise, this salt state was failing because that file was not found.
And if I create this, in addition to `/etc/ssh/sshd_config.d/root.conf` then the ssh connection failed.

2024-06-05 08:47 UTC, meaksh commented on salt/default/init.sls
> +  {% if not grains['osfullname'] in ['SLE Micro', 'SL-Micro'] and not grains['osfullname'] == 'SL-Micro' %}
Shouldn't this be just:

```suggestion
  {% if not grains['osfullname'] == 'SLE Micro' %}
```

2024-06-05 08:47 UTC, meaksh commented on salt/repos/init.sls
> +{% if grains['osfullname'] in ['SLE Micro', 'SL-Micro'] or grains['osfullname'] == 'SL-Micro' %}
I removed the redundant part

```suggestion
{% if grains['osfullname'] in ['SLE Micro', 'SL-Micro'] %}
```

2024-06-05 08:47 UTC, meaksh commented on salt/default/sshd.sls
> +{% if grains['os'] == 'SUSE' and not grains['osrelease'] in ['15.6', '6.0'] %}
I would try to use a better matching, based on `osfullname` grain instead.

2024-06-05 08:52 UTC, srbarrios commented on salt/default/sshd.sls
> +{% if grains['os'] == 'SUSE' and not grains['osrelease'] in ['15.6', '6.0'] %}
Aha, ok.
But it seems to affect only to SL Micro 6.0 and Leap 15.6

2024-06-05 08:53 UTC, srbarrios commented on salt/repos/init.sls
> +{% if grains['osfullname'] in ['SLE Micro', 'SL-Micro'] or grains['osfullname'] == 'SL-Micro' %}
I replaced all the matches and it seems some where already refactored.

2024-06-05 08:53 UTC, srbarrios commented on salt/default/init.sls
> +  {% if not grains['osfullname'] in ['SLE Micro', 'SL-Micro'] and not grains['osfullname'] == 'SL-Micro' %}
I replaced all the matches and it seems some where already refactored.

2024-06-05 09:03 UTC, srbarrios commented on salt/default/sshd.sls
> +{% if grains['os'] == 'SUSE' and not grains['osrelease'] in ['15.6', '6.0'] %}
What about this?
```
{% if not ( grains['osfullname'] in ['Leap', 'SL-Micro'] and grains['osrelease'] in ['15.6', '6.0'] ) %}
```

2024-06-05 09:28 UTC, meaksh requested changes

2024-06-05 09:28 UTC, meaksh commented on salt/default/sshd.sls
> +{% if not ( grains['osfullname'] in ['Leap', 'SL-Micro'] and grains['osrelease'] in ['15.6', '6.0'] ) %}
Isn't `osfullname' for Leap actually `openSUSE Leap Micro` ?  And what about SLES ?

2024-06-05 09:35 UTC, meaksh approved these changes

2024-06-05 09:38 UTC, merged