Add SUMA 5.0
uyuni-project/sumaform pull request #1657
Opened 2024-08-22 17:35 UTC by nodeg

## What does this PR change?

This properly differentiates between the containerized products and also add support for SUMA 5.0 with the correct `mgr*` tools repo.

2024-08-22 17:49 UTC, nodeg commented
A possible solution would also be to add the correct repos to the `cloud-init` config file directly and not use Salt. This can easily be done with more conditions:

```sls
%{ if container_server }
{% if 'uyuni' in grains.get('product_version') %}
    - id: container_tools_repo
      name: container_tools_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs" }/Devel:/Galaxy:/Manager:/Head/images/repo/SUSE-Manager-Server-5.0-POOL-x86_64-Media1/
      enabled: 1
      autorefresh: 1
      gpgcheck: false
{% elif '5.0' in grains.get('product_version') %}
(...)
%{ endif }
%{ endif }
%{ if container_proxy }
{% if 'uyuni' in grains.get('product_version') %}
    - id: container_tools_repo
      name: container_tools_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs" }/Devel:/Galaxy:/Manager:/Head/images/repo/SUSE-Manager-Proxy-5.0-POOL-x86_64-Media1/
      enabled: 1
      autorefresh: 1
      gpgcheck: false
{% elif '5.0' in grains.get('product_version') %}
(...)
%{ endif }
%{ endif }
```

2024-08-23 09:31 UTC, srbarrios commented on salt/repos/init.sls
> -  - repos.proxy_containerized
As `server_containerized` and `proxy_containerized` are different sumaform modules, I prefer to keep organizing the repos as it is.

2024-08-23 09:33 UTC, srbarrios commented on salt/repos/proxy50.sls
> +{% if 'proxy_containerized' in grains.get('roles') and 'uyuni' in grains.get('product_version') %}
`'uyuni'` ? Shouldn't that point to something like '5.0' ?

2024-08-23 09:34 UTC, srbarrios commented on salt/repos/proxy50.sls
> +{% if grains['osfullname'] == 'SLE Micro' %}
I think this should be `'SLE Micro' in grains['osfullname']`

2024-08-23 09:35 UTC, srbarrios commented on salt/repos/proxy50.sls
> +{% if grains.get("os") == "SUSE" %}
Prefer single quotes.

2024-08-23 09:37 UTC, srbarrios commented on salt/repos/proxy50.sls
> +{% if 'proxy_containerized' in grains.get('roles') and 'uyuni' in grains.get('product_version') %}
Btw, that statement is useless, as we already check exactly that inside `salt/repos/proxy_containerized.sls`

2024-08-23 09:40 UTC, srbarrios commented on salt/repos/server.sls
> +  - repos.server_containerized
I would not mix containerized server with regular server.
At least, until we deprecate and remove server module from sumaform.

2024-08-23 09:47 UTC, nodeg commented on backend_modules/libvirt/host/user_data.yaml
> +%{ if container_server && 'released' not in grains.get('product_version')}
I thought so, too, but I was not sure. Thank you for clarifying this.

2024-08-23 09:49 UTC, nodeg commented on salt/repos/init.sls
> -  - repos.proxy_containerized
But when we leave them in, we call them 2 times. If you take a look at the logic (and I simply copied it), we do:
`repos.init.sls` -> `repos.server` ->  `repos.server_containerized` -> `repos.server50`

So once finished with `repos.server` we will again go to `repos.server_containerized`  when we keep the above code.

2024-08-23 09:52 UTC, nodeg commented on salt/repos/proxy50.sls
> +{% if grains.get("os") == "SUSE" %}
Simply copy-pasted from https://github.com/nodeg/sumaform/blob/35aafb2dea8829c77221db543c4af15fc4ef2301/salt/repos/proxy_containerizedUyuni.sls. But I will fix it.

2024-08-23 09:52 UTC, nodeg commented on salt/repos/proxy50.sls
> +{% if grains['osfullname'] == 'SLE Micro' %}
Also simply copy-pasted from https://github.com/nodeg/sumaform/blob/35aafb2dea8829c77221db543c4af15fc4ef2301/salt/repos/proxy_containerizedUyuni.sls

2024-08-23 09:54 UTC, nodeg commented on salt/repos/server.sls
> +  - repos.server_containerized
But we do the same with the proxy, see:
https://github.com/uyuni-project/sumaform/blob/25b8b7442fdf39448942dbf58d7f3290615c3259/salt/repos/proxy.sls#L1-L14

2024-08-23 10:00 UTC, nodeg commented on backend_modules/libvirt/host/user_data.yaml
> +%{ if container_server && 'released' not in grains.get('product_version')}
```bash
│ Error: failed to render : <template_file>:315,27-42: Unknown variable; There is no variable named "product_version"., and 1 other diagnostic(s)
│
│   with module.cucumber_testsuite.module.slemicro-minion.module.minion.module.host.data.template_file.user_data,
│   on sumaform/backend_modules/libvirt/host/main.tf line 54, in data "template_file" "user_data":
│   54: data "template_file" "user_data" {
│
╵
╷
│ Error: failed to render : <template_file>:315,27-42: Unknown variable; There is no variable named "product_version"., and 1 other diagnostic(s)
│
│   with module.cucumber_testsuite.module.server_containerized[0].module.server_containerized.module.host.data.template_file.user_data,
│   on sumaform/backend_modules/libvirt/host/main.tf line 54, in data "template_file" "user_data":
│   54: data "template_file" "user_data" {
```

2024-08-23 10:04 UTC, srbarrios commented on salt/repos/server.sls
> +  - repos.server_containerized
I think I shouldn't have do it like that when I implemented the proxy container..
But ok, if you want to align server and proxy implementation, make sense.

2024-08-23 10:05 UTC, nodeg commented on backend_modules/libvirt/host/user_data.yaml
> +%{ if container_server && 'released' not in grains.get('product_version')}
Ah, I know what I am missing for that.

2024-08-23 10:07 UTC, nodeg commented on salt/repos/proxy50.sls
> +{% if 'proxy_containerized' in grains.get('roles') and 'uyuni' in grains.get('product_version') %}
True. Also copy-pasted, but I removed it.

2024-08-23 10:08 UTC, srbarrios commented on salt/repos/proxy50.sls
> +{% if grains['osfullname'] == 'SLE Micro' %}
Right, it's fine, I though that grain will contain the version.
```
oscar-pxy:/ # salt-call --local grains.get osfullname
local:
    SLE Micro
oscar-pxy:/ # salt-call --local grains.get os        
local:
    SUSE
```

2024-08-23 10:21 UTC, nodeg commented on backend_modules/libvirt/host/user_data.yaml
> +%{ if container_server && 'released' not in grains.get('product_version')}
Fixed.

2024-08-23 10:22 UTC, nodeg commented on salt/repos/proxy50.sls
> +{% if grains.get("os") == "SUSE" %}
Fixed.

2024-08-23 11:19 UTC, ktsamis approved these changes
I can't see anything missing, looks good

2024-08-23 12:00 UTC, nodeg commented
Ok, after testing the PR, I think we need the `mgr*` tools repo earlier meaning in cloud-init already.

2024-08-23 12:57 UTC, vandabarata approved these changes
looks good, thank you so much for taking this on :green_heart:

2024-08-23 13:35 UTC, nodeg commented
The deployment still does not work. It seems the conditions in the `cloud-init` config do not work, yet. I think this is due to the `product_version` variable not being properly set/get.

2024-08-26 16:11 UTC, ktsamis requested changes
small change I think is needed for at least the SLE testsuite, not sure how it would affect BV though, I will test it locally for the SLE testsuite

2024-08-26 16:11 UTC, ktsamis commented on salt/proxy_containerized/init.sls
> +    {% set container_tag = '' %}
I think here we need also latest

2024-08-27 05:30 UTC, nodeg commented on salt/proxy_containerized/init.sls
> +    {% set container_tag = '' %}
We need to get confirmation from hexagon regarding:

```sls
# in SUMA this would use most recent version as tag
```

2024-08-27 07:24 UTC, nodeg commented on salt/proxy_containerized/init.sls
> +    {% set container_tag = '' %}
See the discussion in https://suse.slack.com/archives/C02CLB6AGJ3/p1724739884962369.

2024-08-27 07:49 UTC, nodeg commented on salt/proxy_containerized/init.sls
> +    {% set container_tag = '' %}
Ok, so according to Michele, we should leave it as is:

> No, mgradm for suma should already provide the correct default version, if not it's a bug.

2024-08-27 13:36 UTC, nodeg commented
After taking another look, I am wondering if we really need my new `server50.sls`/`proxy50.sls` files, since they only add the repository that was already added in `cloud-init`.

2024-08-27 13:44 UTC, Bischoff reviewed
See remark

2024-08-27 13:44 UTC, Bischoff commented on modules/controller/main.tf
> +    # TODO once the branch exists
Remove comments here? The branch is about to exist

2024-08-27 13:52 UTC, nodeg commented on modules/controller/main.tf
> +    # TODO once the branch exists
Fixed. Actually the branch is already there.

2024-08-28 09:58 UTC, mbussolotto approved these changes

2024-08-28 10:00 UTC, mcalmer approved these changes
ok to give it a try

2024-08-28 10:03 UTC, nodeg commented
> ok to give it a try

I already tested it in my 5.0 test environment and Kostas in the SLE MU 5.0 test suite pipeline.

2024-08-28 13:33 UTC, nodeg commented
Rebase including squashing done.

2024-08-28 13:34 UTC, merged