Remove RMT registration for Liberty 9
uyuni-project/sumaform pull request #1663
Opened 2024-08-29 13:05 UTC by nodeg

## What does this PR change?

`rmt.scc.suse.de` had issues in the past which caused issues in our BV deployments. With this, we remove this dependency.
See https://github.com/SUSE/spacewalk/issues/24567

2024-08-30 14:55 UTC, vandabarata commented on backend_modules/libvirt/host/user_data.yaml
>    # WORKAROUND: cloud-init in Liberty 9 does not take care of the following
should we remove this comment as well?

2024-08-30 14:55 UTC, vandabarata approved these changes

2024-09-01 08:47 UTC, srbarrios commented
So, there are no salt states from sumaform sls files matching Liberty 9?

2024-09-02 06:42 UTC, nodeg commented on backend_modules/libvirt/host/user_data.yaml
>    # WORKAROUND: cloud-init in Liberty 9 does not take care of the following
No, I would leave it, since it is important for the next 2 line (allowing root access via SSH).

2024-09-02 06:45 UTC, nodeg commented
> So, there are no salt states from sumaform sls files matching Liberty 9?

There is indeed one file where something is mentioned. Thank you, Oscar! I do not know, why I missed that.

2024-09-02 08:00 UTC, srbarrios commented
> > So, there are no salt states from sumaform sls files matching Liberty 9?
> 
> There is indeed one file where something is mentioned. Thank you, Oscar! I do not know, why I missed that.

I would try to follow the same approach that for other systems. So, inject a zypper repo from where it could get venv-salt-minion or salt-minion.

Example:
```
%{ if image == "almalinux9o" }
yum_repos:
  # repo for salt
  tools_pool_repo:
    baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org"}/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/
    enabled: true
    gpgcheck: false
    name: tools_pool_repo
  # repo for nss-mdns
```

2024-09-02 08:01 UTC, srbarrios requested changes
See my proposal please.

2024-09-02 08:39 UTC, nodeg commented
Thank you for the proposal, Oscar. I am wondering, though, why we need the Salt bundle? The onboarding without it went fine.
Do you remember, why we want to install the Salt bundle via cloud-init, although customers would not do it and get it during the onboarding of a Minion?
Regarding adding the other packages, I need to check if that is possible without RMT.

2024-09-02 08:43 UTC, srbarrios commented
> Thank you for the proposal, Oscar. I am wondering, though, why we need the Salt bundle? The onboarding without it went fine. Do you remember, why we want to install the Salt bundle via cloud-init, although customers would not do it and get it during the onboarding of a Minion? Regarding adding the other packages, I need to check if that is possible without RMT.

We need a salt-minion daemon installed in the VM during the deployment in order to execute salt states matching this system in sumafom.

2024-09-02 09:24 UTC, nodeg commented
Aha, that actually makes sense. I will do some more tests around that and see what the cloud image already provides.

2024-09-02 10:15 UTC, nodeg commented
```bash
[root@dominik-min-rhlike ~]# dnf repolist
repo id                                                                                        repo name
epel                                                                                           epel
tools_pool_repo                                                                                tools_pool_repo
[root@dominik-min-rhlike ~]# dnf search venv-salt-minion
Last metadata expiration check: 0:00:23 ago on Mon 02 Sep 2024 06:13:05 AM EDT.
=========================================================================== Name Exactly Matched: venv-salt-minion ===========================================================================
venv-salt-minion.aarch64 : The venvjailed client component for Salt
venv-salt-minion.ppc64le : The venvjailed client component for Salt
venv-salt-minion.s390x : The venvjailed client component for Salt
venv-salt-minion.src : The venvjailed client component for Salt
venv-salt-minion.x86_64 : The venvjailed client component for Salt

[root@dominik-min-rhlike ~]# cat /etc/yum.repos.d/tools_pool_repo.repo
# Created by cloud-init on Mon, 02 Sep 2024 13:47:30 +0000
[tools_pool_repo]
baseurl = http://minima-mirror-ci-bv.mgr.suse.de/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/
enabled = 1
gpgcheck = 0
name = tools_pool_repo

```

So we would have `venv-salt-minion` still available due to adding this repo in cloud-init. See
https://github.com/uyuni-project/sumaform/blob/8ab45edeb6239e868860481960b7f44ce1061f55/backend_modules/libvirt/host/user_data.yaml#L676-L680

2024-09-02 10:34 UTC, srbarrios commented
> ```shell
> [root@dominik-min-rhlike ~]# dnf repolist
> repo id                                                                                        repo name
> epel                                                                                           epel
> tools_pool_repo                                                                                tools_pool_repo
> [root@dominik-min-rhlike ~]# dnf search venv-salt-minion
> Last metadata expiration check: 0:00:23 ago on Mon 02 Sep 2024 06:13:05 AM EDT.
> =========================================================================== Name Exactly Matched: venv-salt-minion ===========================================================================
> venv-salt-minion.aarch64 : The venvjailed client component for Salt
> venv-salt-minion.ppc64le : The venvjailed client component for Salt
> venv-salt-minion.s390x : The venvjailed client component for Salt
> venv-salt-minion.src : The venvjailed client component for Salt
> venv-salt-minion.x86_64 : The venvjailed client component for Salt
> 
> [root@dominik-min-rhlike ~]# cat /etc/yum.repos.d/tools_pool_repo.repo
> # Created by cloud-init on Mon, 02 Sep 2024 13:47:30 +0000
> [tools_pool_repo]
> baseurl = http://minima-mirror-ci-bv.mgr.suse.de/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9/
> enabled = 1
> gpgcheck = 0
> name = tools_pool_repo
> ```
> 
> So we would have `venv-salt-minion` still available due to adding this repo in cloud-init. See
> 
> https://github.com/uyuni-project/sumaform/blob/8ab45edeb6239e868860481960b7f44ce1061f55/backend_modules/libvirt/host/user_data.yaml#L676-L680

Ah perfect! I miss it on my previous review :)
All good then.

2024-09-02 10:35 UTC, srbarrios approved these changes

2024-09-02 11:36 UTC, merged