Remove openSUSE Leap 15.4 due to EOL
uyuni-project/sumaform pull request #1686
Opened 2024-09-09 14:02 UTC by nodeg

## What does this PR change?

openSUSE 15.4 is EOL since the end of 2023. See https://en.opensuse.org/Lifetime

2024-09-11 11:20 UTC, vandabarata commented on main.tf.libvirt-testsuite.example
> +  # "opensuse156o", "opensuse155o",
nitpicky, I know, but... 
```suggestion
  # "opensuse155o", "opensuse156o",
```

2024-09-11 11:20 UTC, vandabarata commented on main.tf.libvirt-testsuite.example.Manager-43
> +  # "opensuse156o", "opensuse155o",
same here :sweat_smile:

2024-09-11 11:20 UTC, Bischoff requested changes
see nitpicks

2024-09-11 11:20 UTC, Bischoff commented on main.tf.libvirt-testsuite.example
> +  # "opensuse156o", "opensuse155o",
sort by increasing number please, like we do for centos, for consistency

2024-09-11 11:20 UTC, Bischoff commented on main.tf.libvirt-testsuite.example.Manager-43
> +  # "opensuse156o", "opensuse155o",
same

2024-09-11 11:21 UTC, vandabarata commented on main.tf.libvirt-testsuite.example
> +  # "opensuse156o", "opensuse155o",
we have the same nitpicks :rofl:

2024-09-11 11:30 UTC, vandabarata approved these changes

2024-09-11 11:32 UTC, Bischoff approved these changes

2024-09-12 07:41 UTC, srbarrios requested changes
Please fix the code in Sumaform tests before merging it.

2024-09-13 09:55 UTC, Bischoff commented
> Please fix the code in Sumaform tests before merging it.

Sorry, i need those changes for my 4.3.14 BV and I don't have the time to look at that. It's also very likely to be a false positive. Merging.

2024-09-13 10:21 UTC, Bischoff requested changes
Please close. I fixed the PR in https://github.com/uyuni-project/sumaform/pull/1697

2024-09-13 10:22 UTC, Bischoff commented
I fixed the PR in #1697

2024-09-13 10:22 UTC, closed without merging