Add dummy AppStream repository
uyuni-project/sumaform pull request #1695
Opened 2024-09-12 11:23 UTC by NamelessOne91

## What does this PR change?

Port of https://github.com/uyuni-project/sumaform/pull/1693

2024-09-12 11:56 UTC, Bischoff requested changes
I think the target project and the target branch are wrong:

uyuni-project:suma-5.0 ==> SUSE:Manager-5.0

2024-09-12 12:31 UTC, Bischoff approved these changes

2024-09-12 12:31 UTC, Bischoff commented
> I think the target project and the target branch are wrong:
> 
> uyuni-project:suma-5.0 ==> SUSE:Manager-5.0

forget it, i missed it was for sumaform

2024-09-13 15:10 UTC, NamelessOne91 commented
This backport is not needed

2024-09-13 15:10 UTC, closed without merging