Refactor the usage of packages keyword in cloud-init, to avoid auto upgrade of packages
uyuni-project/sumaform pull request #1705
Opened 2024-09-24 12:21 UTC by srbarrios

## What does this PR change?

Don't upgrade packages in the systems deployed in a SUMA/Uyuni test environment.

- Related card: https://github.com/SUSE/spacewalk/issues/25189

The cloud team added the module `package-update-upgrade-install` to SUSE cloud-init configuration. This triggers an not-desired update of packages in some of the systems part of our test environment.

This is triggered due to the usage of the keyword `packages` in our [YAML file](https://github.com/uyuni-project/sumaform/blob/master/backend_modules/libvirt/host/user_data.yaml#L91).

---

This PR replace the keyword `packages` by `runcmd zypper in`

Example:
```
packages: ["venv-salt-minion", "avahi", "nss-mdns", "qemu-guest-agent"]
```
```
runcmd:
  - zypper in venv-salt-minion avahi nss-mdns qemu-guest-agent
```

2024-09-24 12:54 UTC, Bischoff approved these changes

2024-09-24 12:57 UTC, NamelessOne91 approved these changes

2024-09-24 13:27 UTC, ktsamis requested changes
I think these need -y as well like some apt commands below

2024-09-24 13:27 UTC, ktsamis commented on backend_modules/libvirt/host/user_data.yaml
> +  - apt install venv-salt-minion avahi-daemon qemu-guest-agent
This needs also to be non interactive right?

2024-09-24 13:27 UTC, ktsamis commented on backend_modules/libvirt/host/user_data.yaml
> +  - apt install salt-minion avahi-daemon qemu-guest-agent
Same non interactive?

2024-09-24 13:27 UTC, ktsamis commented on backend_modules/libvirt/host/user_data.yaml
> +  - apt install venv-salt-minion avahi-daemon qemu-guest-agent
Same

2024-09-24 13:27 UTC, ktsamis commented on backend_modules/libvirt/host/user_data.yaml
> +  - apt install salt-minion avahi-daemon qemu-guest-agent
Same

2024-09-24 14:54 UTC, srbarrios commented
Something still wrong for Ubuntu2204 VM and SLES15SP4 BuildHost VM.
To be debugged.

2024-09-26 13:17 UTC, Bischoff requested changes
see remark about runcmd: sections

2024-09-30 07:47 UTC, srbarrios commented on backend_modules/libvirt/host/user_data.yaml
> +runcmd:
Thank you Eric, done!

2024-09-30 11:24 UTC, NamelessOne91 commented on backend_modules/libvirt/host/user_data.yaml
> +  - "dnf -y install in salt-minion avahi nss-mdns qemu-guest-agent"
is the "in" a copy-paste error ?

2024-09-30 11:25 UTC, ktsamis approved these changes
Looks good now

2024-09-30 12:05 UTC, srbarrios commented on backend_modules/libvirt/host/user_data.yaml
> +  - "dnf -y install in salt-minion avahi nss-mdns qemu-guest-agent"
in deed

2024-09-30 13:26 UTC, Bischoff requested changes
see nitpicks + 1 question

2024-09-30 13:26 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
>  # For openSUSE Tumbleweed venv-salt-minion is not available.
Move this comment down, just before the zypper install

2024-09-30 13:26 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
> +runcmd:
add blank line above

2024-09-30 13:26 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
>  %{ if image == "ubuntu2204o" }
we probably lack a blank line before this one

2024-09-30 13:26 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
> +  - "apt-get -yq install salt-minion avahi-daemon qemu-guest-agent"
question: why do we sometimes have DEBIAN_FRONTEND=noninteractive and sometimes not?

sorry if noob question

2024-09-30 13:26 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
> +  - "apt-get -yq update"
thanks

2024-09-30 13:30 UTC, srbarrios commented on backend_modules/libvirt/host/user_data.yaml
> +  - "apt-get -yq install salt-minion avahi-daemon qemu-guest-agent"
I find it already added in Debian images, so I just kept using it there.
On Ubuntu, I don't even tried.

2024-09-30 13:34 UTC, Bischoff commented on backend_modules/libvirt/host/user_data.yaml
> +  - "apt-get -yq install salt-minion avahi-daemon qemu-guest-agent"
ok

2024-09-30 13:35 UTC, Bischoff approved these changes
thanks for the nitpick corrections

2024-09-30 13:36 UTC, merged