Remove variables not impacting the deployment.
uyuni-project/sumaform pull request #1736
Opened 2024-10-09 23:58 UTC by maximenoel8

Make server_configuration optional for proxy and client.

## What does this PR change?
- Remove variables not impacting the deployment.
- Make server_configuration optional for proxy and client.

2024-10-10 06:14 UTC, ktsamis approved these changes
I don't see a problem with this

2024-10-10 08:05 UTC, srbarrios commented
The build host, buid docker images.
Looking at salt states, you are right, we don't seem to have avahi_reflector used anywhere else aside minion, but... maybe we should do the opposite and support it there?

@Bischoff could you bring some light before approving this PR please?

2024-10-10 08:05 UTC, srbarrios requested changes
Waiting @Bischoff feedback about avahi_reflector support in a Build Host

2024-10-10 08:16 UTC, srbarrios commented on modules/build_host/main.tf
> -    auto_connect_to_master = var.auto_connect_to_master
From the point of view of `auto_connect_to_master` feature, I think it make sense to have the possibility to auto connect a build host, at the end is just another salt minion that we onboard with a special Add-On system type.

Instead of removing it because is unused at that moment, I would consider to change its parent from `host` to `minion`. So that would make possible for a build_host to autoconnect to master.

2024-10-10 10:26 UTC, maximenoel8 commented on modules/build_host/main.tf
> -    auto_connect_to_master = var.auto_connect_to_master
It's just that it has never been used for a long while ( maybe ever ). I was thinking adding the auto connect to build host, but if it's not needed now, I don't see a need for later.
I will ping Pablo to have a look at this PR.

2024-10-10 10:27 UTC, maximenoel8 commented
> The build host, [build docker images](https://documentation.suse.com/suma/4.3/en/suse-manager/administration/image-management.html#at.images.docker.building). Looking at salt states, you are right, we don't seem to have avahi_reflector used anywhere else aside minion, but... maybe we should do the opposite of the proposed change and support avahi_reflector in build_host, to do so, I think it's enough to change its parent from `host` to `minion`.
> 
> @Bischoff could you bring some light before approving this PR please?

Do we have a use case ? Sumaform is already complex, by digging I found those unused variables. It has been like that for a while.

2024-10-10 10:33 UTC, Bischoff commented
> > The build host, [build docker images](https://documentation.suse.com/suma/4.3/en/suse-manager/administration/image-management.html#at.images.docker.building). Looking at salt states, you are right, we don't seem to have avahi_reflector used anywhere else aside minion, but... maybe we should do the opposite of the proposed change and support avahi_reflector in build_host, to do so, I think it's enough to change its parent from `host` to `minion`.
> > @Bischoff could you bring some light before approving this PR please?
> 
> Do we have a use case ? Sumaform is already complex, by digging I found those unused variables. It has been like that for a while.

If you deploy a build host on your workstation where you use avahi, you will need the reflector. I would call this a use case.

We don't see it in our official test suites because they all rely on a DNS server.

I think Oscar is correct here. Either don't apply, or refactor to be able to use it on a build host.

2024-10-10 10:35 UTC, Bischoff commented on modules/build_host/main.tf
> -    auto_connect_to_master = var.auto_connect_to_master
I used to use avahi quite a lot. 

We don't need auto connect on the build host (*), but we do need the avahi reflector.


(*) at least not me, but maybe some developer or supporter does. Oscar mentioned that in demoes our supporters use that auto connect thing intensively.

2024-10-10 10:38 UTC, Bischoff requested changes
same concerns as Oscar

2024-10-10 12:10 UTC, meaksh commented on modules/build_host/main.tf
> -    auto_connect_to_master = var.auto_connect_to_master
I would agree with Óscar on moving the `build_host` from `host` to `minion` and then keeping the auto-connect with master feature.

As developer, I use avahi on my deployments all the times, OTOH I never use this reflector config, which seems not be actually working at the moment for `build_host` (as only does stuff on minion SLS files)

2024-10-11 05:24 UTC, srbarrios approved these changes

2024-10-11 07:15 UTC, Bischoff approved these changes

2024-10-11 07:16 UTC, Bischoff approved these changes

2024-10-13 19:58 UTC, merged