Fix: add section to troubleshoot Avahi and mDNS
uyuni-project/sumaform pull request #771
Opened 2020-09-15 22:20 UTC by mbologna

## What does this PR change?

I was resolution problems with Avahi on an openSUSE 15.2 host trying to resolve a sumaform'ed Uyuni server:

```
opensuse # avahi-resolve -n uyuni.tf.local
uyuni.tf.local 192.168.122.154
# ping uyuni.tf.local
ping: uyuni.tf.local: Name or service not known
# ping 192.168.122.154
PING 192.168.122.154 (192.168.122.154) 56(84) bytes of data.
64 bytes from 192.168.122.154: icmp_seq=1 ttl=64 time=0.245 ms
```

The problem disappears when I change Avahi configuration in the Uyuni host to use the first-level domain `local` (instead of `tf.local`).

Turns out that in the newest version of `nss-mdns` (shipping with OpenSUSE 15.2), second-level `.local` domains must be explicitly allowed to be resolved in `/etc/mdns.allow` AND `mdns` (not `mdns_minimal) must be used in `nsswitch.conf`.
The latter is already covered in the troubleshooting, I took care of adding the former information into the docs.

Upstream issue: https://github.com/lathiat/nss-mdns/issues/64
Upstream resolution (linked in sumaform docs): https://github.com/lathiat/nss-mdns/blob/master/README.md#etcmdnsallow

2020-09-16 08:48 UTC, witekest reviewed
I also observe this behavior on openSUSE 15.2. Populating `/etc/mdns.allow` fixes the problem as described.

2020-09-16 09:12 UTC, rjmateus commented on TROUBLESHOOTING.md
> + - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n mbologna-uyuni.tf.local`
`avahi-resolve` came instaled by default or should we point that `avahi-utils` package should be installed?

2020-09-16 09:14 UTC, mbologna commented on TROUBLESHOOTING.md
> + - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n mbologna-uyuni.tf.local`
The actual package name containing `avahi-resolve` might depend on the distribution though

2020-09-16 09:38 UTC, agraul commented on TROUBLESHOOTING.md
> + - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n mbologna-uyuni.tf.local`
In Debian (10) the package is also called `avahi-utils`, in Fedora (32) it is called `avahi-tools`. We could mention that `avahi-resolve` is typically in an additional package that is commonly suffixed `-tools` or `-utils`, depends on how throughout we want to be here.

2020-09-16 09:43 UTC, Bischoff requested changes
some changes requested (a few nitpicks, but also something important i suggest using same contents for `/etc/mdns.allow` that sumaform uses :smile_cat: )

2020-09-16 09:43 UTC, Bischoff commented on TROUBLESHOOTING.md
> + - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n mbologna-uyuni.tf.local`
mbologna-uyuni -> something more neutral

2020-09-16 09:43 UTC, Bischoff commented on TROUBLESHOOTING.md
>   - avahi is installed and running
avahi -> Avahi

2020-09-16 09:43 UTC, Bischoff commented on TROUBLESHOOTING.md
> +.local
Rather this
```
.local
.local.tf
```

2020-09-16 09:43 UTC, Bischoff commented on TROUBLESHOOTING.md
> +`mdns.allow` is required to [force all .local domains to be resolved regardless of label count or unicast SOA records](https://github.com/lathiat/nss-mdns/blob/master/README.md#etcmdnsallow).
all .local domains -> all multicast DNS domains
(because we use it for `.local.tf`, not for `.local`)

2020-09-17 08:17 UTC, mbologna commented on TROUBLESHOOTING.md
> + - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n mbologna-uyuni.tf.local`
I would not go into the details of which package contains avahi-resolve. It is also true that `cnf` (`command-not-found`) is taking care of suggesting the right package in case someone launches a command and the command is not found.

2020-09-17 08:20 UTC, mbologna commented on TROUBLESHOOTING.md
>   - avahi is installed and running
Fixed

2020-09-17 08:21 UTC, mbologna commented on TROUBLESHOOTING.md
> +.local
Shouldn't that be:

`.local`
`.tf.local`

instead?

2020-09-17 08:21 UTC, mbologna commented on TROUBLESHOOTING.md
> +`mdns.allow` is required to [force all .local domains to be resolved regardless of label count or unicast SOA records](https://github.com/lathiat/nss-mdns/blob/master/README.md#etcmdnsallow).
Fixed

2020-09-17 08:24 UTC, moio commented on TROUBLESHOOTING.md
> +.local
FMPOV this can be merged as soon as this discussion is resolved, thanks @mbologna

2020-09-17 08:50 UTC, agraul commented on TROUBLESHOOTING.md
> + - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n mbologna-uyuni.tf.local`
Fair enough, we don't need to mention package names. JFYI `command-not-found` is not that great of a general solution, it is not pre-installed on all systems (at least not on the Debian and Fedora VMs I'm running).

2020-09-17 09:53 UTC, Bischoff commented on TROUBLESHOOTING.md
> + - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n mbologna-uyuni.tf.local`
What about my remark about not mentioning mbologna in tge example ?

2020-09-17 09:54 UTC, Bischoff commented on TROUBLESHOOTING.md
> +.local
er yes, sorry i inverted

2020-09-17 09:55 UTC, Bischoff commented on TROUBLESHOOTING.md
> +`mdns.allow` is required to [force all .local domains to be resolved regardless of label count or unicast SOA records](https://github.com/lathiat/nss-mdns/blob/master/README.md#etcmdnsallow).
I don't see the fix... but after all, `.tf.local` is also a `.local` domain... :-)

2020-09-17 15:59 UTC, mbologna commented on TROUBLESHOOTING.md
> + - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n mbologna-uyuni.tf.local`
I was waiting for https://github.com/uyuni-project/sumaform/pull/771#discussion_r490060362 to be answered before pushes the fixes. The requested fix is now pushed.

2020-09-18 12:26 UTC, Bischoff approved these changes
LGTM now

2020-09-21 08:54 UTC, merged