Reduce the content checkout from github to the ctl
uyuni-project/sumaform pull request #783
Opened 2020-10-16 12:45 UTC by srbarrios

## What does this PR change?

Inside the controller, we only make use of the `testsuite` folder, so there is no need to download the rest of the repository.
Our current shallow clone takes about 354M, with this change the repository folder will size 12M.

2020-10-16 12:56 UTC, ktsamis approved these changes
makes sense to me to reduce only to the folder we need. Let's try it and see if anything else is needed. Looks great though

2020-10-16 13:04 UTC, calancha commented
This looks like a nice improvement.
First we need to check that the Git version installed in the controller supports those options.
That will likely happen when the ctl is opensuse152o.
For opensuse150o it seems not the case, because that OS ships with Git v**2.16.4,** but the `--filter` since to appear in v**2.170**.

2020-10-16 14:00 UTC, srbarrios commented
> This looks like a nice improvement.
> First we need to check that the Git version installed in the controller supports those options.
> That will likely happen when the ctl is opensuse152o.
> For opensuse150o it seems not the case, because that OS ships with Git v**2.16.4,** but the `--filter` since to appear in v**2.170**.

Very good catch. This PR will need to wait then.

2020-10-18 13:15 UTC, Bischoff requested changes
As Tino found out, this will need to wait a bit because of required git version.

Please also rebase it on top of latest version of sumaform. It should be relatively straightforward, you just need to modify the new `git_helper` script.

2020-10-19 08:35 UTC, moio commented on salt/controller/init.sls
> +        git clone --depth 1 --filter=blob:limit=50K --no-checkout https://github.com/uyuni-project/uyuni.git /root/spacewalk
Will this mean our setup could break when we add files bigger than 50k?

2020-10-19 09:55 UTC, juliogonzalez commented on salt/controller/init.sls
> +        git clone --depth 1 --filter=blob:limit=50K --no-checkout https://github.com/uyuni-project/uyuni.git /root/spacewalk
This doesn't fail, this filters.

If one of the "not cloned" files is part of the testsuite, then of course the testsuite will have problems running.

2020-10-19 09:57 UTC, juliogonzalez approved these changes
Other than the comments about the PR being blocked until we update the controller image, this LGTM.

2020-10-19 10:02 UTC, moio commented on salt/controller/init.sls
> +        git clone --depth 1 --filter=blob:limit=50K --no-checkout https://github.com/uyuni-project/uyuni.git /root/spacewalk
> This doesn't fail, this filters.

Does filter mean such big files would not be downloaded? Because in that case I would assume the teststuite to fail. Did I get that right?

2020-10-19 10:05 UTC, srbarrios commented on salt/controller/init.sls
> +        git clone --depth 1 --filter=blob:limit=50K --no-checkout https://github.com/uyuni-project/uyuni.git /root/spacewalk
It might be indeed not the best solution @moio, have you another proposal to reduce the amount of data downloaded from github every time we prepare a controller? I have in mind things like a sub-module... but I don't like too much that approach.
We can also make use of released zips containing only testsuite folder but thenn we'll not be able to to push/pulls inside the controller...  So that was a kind of trade-off solution.

2020-10-19 10:14 UTC, lkotek approved these changes
LGTM :-)

2020-10-19 10:16 UTC, juliogonzalez commented on salt/controller/init.sls
> +        git clone --depth 1 --filter=blob:limit=50K --no-checkout https://github.com/uyuni-project/uyuni.git /root/spacewalk
> Does filter mean such big files would not be downloaded? Because in that case I would assume the teststuite to fail. Did I get that right?

Can you why should it?

I don't expect testsuite files to be more than 50K, they are just text files with cucumber/ruby code. If for some reason they exceed it, we can adjust it.

> We can also make use of released zips containing only testsuite folder but thenn we'll not be able to to push/pulls inside the controller... So that was a kind of trade-off solution.

Not sure what you mean. Released zips are only generated with you create releases, and contain the whole code for a given commit, not only the testsuite folder. And while we could automate the creation, I don't think we should create GitHub releases all the time for a CI.

What you could s getting the full zip from the branch you want. That's what Eric did on the other PR. You will download the same in the end, but of course maybe it's more efficient from GitHub's point of view.

2020-10-26 08:41 UTC, moio commented
@srbarrios can you try out the approach described here? 

https://medium.com/pinterest-engineering/how-a-one-line-change-decreased-our-build-times-by-99-b98453265370

It seems safer than arbitrarily putting a size limit on blobs, and I wonder if it could yield to even bigger savings.

2020-10-26 09:05 UTC, srbarrios commented
> @srbarrios can you try out the approach described here?
> 
> https://medium.com/pinterest-engineering/how-a-one-line-change-decreased-our-build-times-by-99-b98453265370
> 
> It seems safer than arbitrarily putting a size limit on blobs, and I wonder if it could yield to even bigger savings.

On vacation today, but I'm sure that even if you only check the size of our repository without the .git folder, it will be bigger than 250 megas. So if we want to download less content, this will not solve anything.

2020-10-26 09:10 UTC, moio commented
Then I might suggest a sparse checkout, where one only downloads a subset of the directories, instead of filtering by size.

Seems to be possible: https://stackoverflow.com/questions/4114887/is-it-possible-to-do-a-sparse-checkout-without-checking-out-the-whole-repository

2020-10-26 12:45 UTC, srbarrios commented
> Then I might suggest a sparse checkout, where one only downloads a subset of the directories, instead of filtering by size.
> 
> Seems to be possible: https://stackoverflow.com/questions/4114887/is-it-possible-to-do-a-sparse-checkout-without-checking-out-the-whole-repository

Actually... this PR is not just filtering by size, but also downloading only the testsuite folder.
But I never listened about the sparse checkout and I will be happy to try it.

2021-02-17 16:18 UTC, srbarrios commented
@moio @rjmateus I refactored to use `sparse-checkout` as Moio suggested.
I tested manually and works. Can I merge it?

2021-02-19 15:43 UTC, srbarrios commented
As I want that working for this weekend, I'm going to merge it.
If it cause some troubles, I will revert on Monday.

2021-02-19 15:43 UTC, merged