Extra checks when configuring Avahi
uyuni-project/sumaform pull request #817
Opened 2020-12-15 11:19 UTC by srbarrios

## What does this PR change?

Some tips when troubleshooting Avahi from my local to a deployed VM.

2020-12-15 11:26 UTC, Bischoff requested changes
thanks; some changes

2020-12-15 11:26 UTC, Bischoff commented on TROUBLESHOOTING.md
> + - Your firewall allows `mdns` on libvirt zone
firewall is already mentioned above (but specifies "public" instead of "libvirt"

2020-12-15 11:26 UTC, Bischoff commented on TROUBLESHOOTING.md
>   - Avahi is capable of resolving the host you are trying to reach: `avahi-resolve -n uyuni.tf.local`
maybe `<host>` instead of `uyuni`

2020-12-15 11:26 UTC, Bischoff commented on TROUBLESHOOTING.md
>    - on SUSE systems check YaST -> Security and Users -> Firewall -> Zones -> public, "mdns" should appear on the list on the right
"libvirt" instead of "public" (or specify both with "or")

2020-12-15 11:29 UTC, Bischoff approved these changes
perfect now, thanks

2020-12-15 11:29 UTC, merged

2020-12-16 11:14 UTC, moio commented
Thanks @srbarrios !!!