Added output.tf.example to the main terraform root folder
uyuni-project/sumaform pull request #820
Opened 2020-12-17 11:08 UTC by atighineanu

## What does this PR change?
This PR:
 - allows user to format their own tf.output (by using output.tf.example as source)
 - exposes IPs in the libvirt.host backend module

2020-12-17 11:41 UTC, Bischoff requested changes
nice improvements

see suggestions

2020-12-17 11:41 UTC, Bischoff commented on backend_modules/libvirt/host/main.tf
> +    //displays IPs of libvirt domains; use "value_used.network_interface[0].addresses[0]" if you want just IPv4 to be displayed
I would rather remove blank line and comment - this is by no way different than what preceeds, so itt's not useful to comment

2020-12-17 11:41 UTC, Bischoff commented on backend_modules/libvirt/host/main.tf
> +    ips       = [for value_used in libvirt_domain.domain : value_used.network_interface[0].addresses if length(value_used.network_interface) > 0]
just add `[0]` to the end as we mostly use IPv4s to connect to the VMs

2020-12-17 11:41 UTC, Bischoff commented on output.tf.example
> +output "machines" {  # you can use any title you want instead of "machines"
I would suggest to not do this as a snippet. Rather document it in plain English in `README_ADVANCED.md`

2020-12-17 16:03 UTC, rjmateus reviewed
Thanks for your contribution. Just some small note and I agree with Eric's review.

2020-12-17 16:03 UTC, rjmateus commented on backend_modules/libvirt/host/main.tf
> +
This empty line needs to be removed or the PR checks will not pass. 
Comment can also be removed.

2021-04-22 13:32 UTC, rjmateus commented
@atighineanu the PR's title and description don't match the code changes. This is only exposing the IPs on libvirt host module

2021-05-06 21:13 UTC, rjmateus commented on backend_modules/gcp/host/variables.tf
> +variable "project_name" {
This file is normally a symbolic link to the host variables file inside the null provider. You can check the other supported providers.
The idea behind it is that sumaform users can use any provider without the need to change several properties in the configuration. 
Also, the module inside `modules/host` can call the same API and don't care about what underlying provider are in use.

2023-07-24 12:06 UTC, srbarrios commented
This looks a deprecated PR that can be closed.
@atighineanu would be fine to close it?

2023-07-24 20:08 UTC, atighineanu commented
> This looks a deprecated PR that can be closed.
> 
> @atighineanu would be fine to close it?

Sure. There are two years since I have lost contact to sumaform.

2023-07-27 20:47 UTC, cbbayburt commented
Closing as obsolete

2023-07-27 20:47 UTC, closed without merging