Add build_validation variable
uyuni-project/sumaform pull request #850
Opened 2021-02-01 17:30 UTC by ktsamis

## What does this PR change?

Add build_validation variable to differentiate between CI runs and QAM/Build validations. We need this to fix https://github.com/SUSE/spacewalk/issues/13849

Goes together with: https://github.com/SUSE/susemanager-ci/pull/183

2021-02-01 20:24 UTC, srbarrios commented on salt/controller/bashrc
> +
I personally don't like this approach.
I would like to keep sumaform agnostic from the kind of test we run.

Instead, I would handle this variable in Terracumber, as we do when we inject the custom_repositories.json in the controller through Terracumber.

2021-02-02 09:06 UTC, Bischoff approved these changes
LGTM. Please use sumaform approach.

2021-02-02 09:06 UTC, Bischoff commented on salt/controller/bashrc
> +
No, no, no :-) . Please.

I want to be able to deploy myself (no jenkins) => sumaform.

And even when deployed by Jenkins, when I test manually, I do not want to need to do `export BUILD_VALIDATION=true` by hand every time i test.

2021-02-02 09:10 UTC, srbarrios requested changes
Please. Don't merge this.
Discuss it first with @moio and @rjmateus , I think sumaform must be agnostic from the kind of test we will run. Also in my opinion, we are overengineering in that case.
We can handle this variable directly from the pipeline, and if you don't run it using Jenkins, or Terracumber, you can always go to the controller and add the variable in your .bashrc

Proposal: https://github.com/SUSE/susemanager-ci/pull/184

2021-02-02 09:10 UTC, Bischoff requested changes
Nice, but incomplete : you need to define the variable, give it a default value, pass it on as a grain...

2021-02-02 09:17 UTC, Bischoff commented
> We can handle this variable directly from the pipeline, and if you don't run it using Jenkins, or Terracumber, you can always go to the controller and add the variable in your .bashrc

What if there is no pipeline, and I want to run sumaform as usual?

And no, i don't want to start adding variables by hand to .bashrc.

2021-02-02 09:29 UTC, rjmateus commented on salt/controller/bashrc
> +{% if grains.get('build_validation') | default(false, true) %}export BUILD_VALIDATION="true" {% else %}# normal CI {% endif %}
Who is responsible for writing the grains `build_validation`. I don't see it in this PR.

2021-02-02 09:30 UTC, Bischoff commented on salt/controller/bashrc
> +{% if grains.get('build_validation') | default(false, true) %}export BUILD_VALIDATION="true" {% else %}# normal CI {% endif %}
yes, the PR is incomplete, see my review comment

2021-02-02 09:48 UTC, ktsamis commented on salt/controller/bashrc
> +{% if grains.get('build_validation') | default(false, true) %}export BUILD_VALIDATION="true" {% else %}# normal CI {% endif %}
This would be in the main.tf we use as a custom grain https://github.com/SUSE/susemanager-ci/pull/183 we can of course set it in the controller always via sumaform, I can modify this

2021-02-02 10:19 UTC, ktsamis commented
After discussions we will remove this completely. not needed anymore

2021-02-02 10:19 UTC, closed without merging