Beta urls
uyuni-project/sumaform pull request #858
Opened 2021-02-12 14:36 UTC by ktsamis

## What does this PR change?

Correct res and sle11 beta urls for mirror from BETA to Beta. 
Also fix detection of release in RES 7 case for tools_pool_repo

2021-02-12 14:37 UTC, ktsamis commented
@moio I put you as reviewer because I'm not sure about the commit about detection 937c1a7 it's been there for a while and I'm surprised we didn't see it before. Am I wrong in fixing it? Maybe it is correct?

2021-02-12 14:52 UTC, juliogonzalez requested changes
Are you sure the changes from `BETA`  to `Beta` are needed in all cases? At least the last change is clearly wrong.

2021-02-12 14:52 UTC, juliogonzalez commented on salt/repos/default.sls
> +    {% elif release == 7 %}
Well... don't really understand why this change is here, but if you tested it, I guess it's OK

2021-02-12 14:52 UTC, juliogonzalez commented on salt/repos/default.sls
> +    - baseurl: http://{{ grains.get("mirror") | default("download.suse.de/ibs", true) }}/SUSE/Updates/RES/{{ release }}-CLIENT-TOOLS-Beta/x86_64/update/
This is NOT Ok.

Check https://download.suse.de/ibs/SUSE/Updates/RES/ and you will see all beta client tools are `N-CLIENT-TOOLS-BETA` Could it be you have problems at your mirror?

2021-02-12 16:21 UTC, juliogonzalez approved these changes
LGTM now.

2021-02-12 16:23 UTC, merged

2021-02-15 08:47 UTC, srbarrios commented
@juliogonzalez @ktsamis I think I already commented about these lines in the past. I think we should homogenize the way to handle the mirror in our repos. Instead of using this if statement that is hard to read, I would use the format we are using in other states by replace the domain directly inside the repo url.