Add scc support for aws deployment
uyuni-project/sumaform pull request #919
Opened 2021-07-13 02:19 UTC by maximenoel8

## What does this PR change?

The use of internal repositories for public imply the use of mirror. The use of this mirror make the deployment very time consuming.

The idea of this PR is  to have the possibility to use SCC repositories when deploying on AWS. So when we want to test AWS deployment, we will only need to mirror repositories needed for the test and don't need to mirror all the default repositories.

The scc is an added behavior that change nothing  on default deployment. 

To use it, you need to add to module `base` the variable `server_registry_code` in your main.tf

The code has to be a Suse Manager Server activation code.

2021-07-20 09:15 UTC, moio commented
This would actually make sense across backends - unless I am missing something this is not an AWS-specific scenario.

2021-07-20 09:30 UTC, rjmateus commented
> This would actually make sense across backends - unless I am missing something this is not an AWS-specific scenario.

I Agree with Moio, and I would make sense for all backends. The implementation is also using the shared variables, so it should be implemented in all backends.
For backend-specific variables, we should pass data in the provider-settings map variable.

2021-07-20 12:13 UTC, Bischoff requested changes
see inline comments, plus:

* same as Moio's and Ricardo's remarks
* it lacks explanation in `README_ADVANCED.md`
* beware that using SCC directly is a nice possibility, but it exposes us to:
    * failures at SCC
    * the case where a package is being updated at SCC right now
    * also, I'm not sure about bandwidth between the cloud and SCC

2021-07-20 12:13 UTC, Bischoff commented on backend_modules/null/base/variables.tf
> +  description = "Use scc register"
SCC capital letters

do you mean "registration" instead of "register"?

2021-07-20 12:13 UTC, Bischoff commented on modules/base/main.tf
> +  server_registry_code = var.server_registry_code
`registration` ?

what's this code ? if it's this `UC7` thing I think we already have it in another variable.

2021-07-20 12:13 UTC, Bischoff commented on modules/base/variables.tf
> +  default     = "null"
use empty string `""` as null value ?

2021-07-20 12:13 UTC, Bischoff commented on salt/repos/server.sls
> +{% if '4.0' in grains['product_version'] and not grains.get('server_registry_code') %}
will this `not` work with the `'null'` value?

2021-07-20 13:30 UTC, rjmateus reviewed
Thanks for the contribution.
I drop some comments.

2021-07-20 13:30 UTC, rjmateus commented on backend_modules/aws/base/main.tf
> +  server_registry_code = var.server_registry_code
this variable is declared but never used.

2021-07-20 13:30 UTC, rjmateus commented on backend_modules/aws/host/user_data.yaml
> +%{ if server_registry_code != "null" }
If we use the null type instead of null string, I'm not sure if this check will still work. 
Some tests are needed to make sure the test is behaving as expected.

2021-07-20 13:30 UTC, rjmateus commented on backend_modules/aws/host/user_data.yaml
> +runcmd:
For readability, I think this if statements are goog.
But did you consider move the common parts to outside the if, and the condiction only generating the different connect statements?
Example:
```
runcmd:
  - SUSEConnect --url https://scc.suse.com -r ${server_registry_code}
%{ if image == "sles15sp1o" }
  - SUSEConnect -p sle-module-python2/15.1/x86_64
  - SUSEConnect -p sle-module-web-scripting/15.1/x86_64
  - SUSEConnect -p sle-module-suse-manager-server/4.0/x86_64
%{ endif }
  - zypper in -y salt-minion
```

2021-07-20 13:30 UTC, rjmateus commented on modules/base/variables.tf
> +  default     = "null"
Or use the `null` type, as we have in line 28 of this file.

2021-07-20 13:30 UTC, rjmateus commented on backend_modules/null/base/variables.tf
> +  default     = "null"
I think we should the `null` type in here instead of string null

2021-07-20 13:30 UTC, rjmateus commented on salt/repos/default.sls
> +{% if '15.1' == grains['osrelease'] and grains['server_registry_code'] == 'null' %}
The comparation is made in two different ways. For example in file `salt/repos/server.sls` it is done in the form:
`... and not grains.get('server_registry_code') `

What should be the correct way to check if the varaible is empty? 
That will depend if we use the null type?

2021-07-20 13:30 UTC, rjmateus commented on salt/repos/default.sls
> +{% if '15.2' == grains['osrelease'] and grains['server_registry_code'] == 'null' %}
some comment as above.

2021-07-20 13:30 UTC, rjmateus commented on salt/server/init.sls
> +{% if '4' in grains['product_version'] and grains['osfullname'] != 'Leap' and grains['server_registry_code'] == 'null' %}
some comment as above

2021-07-21 01:37 UTC, maximenoel8 commented on modules/base/main.tf
> +  server_registry_code = var.server_registry_code
No, it's not the proxy code you need to enter but the SUMA SCC registration code.

2021-07-21 01:42 UTC, maximenoel8 commented on modules/base/variables.tf
> +  default     = "null"
I use "null" in quote because using null was breaking my code and I didn't find a better solution.

The issue is if `default = null` then `%{ if server_registration_code != "null" }` in user_data.yaml has an error because the value `server_registration_code` doesn't exist by default.

I will try using `""`, I don't know how the salt/grain will convert that value

If you have any better idea how to manage this I'm open to suggestion.

2021-07-21 01:44 UTC, maximenoel8 commented on salt/repos/server.sls
> +{% if '4.0' in grains['product_version'] and not grains.get('server_registry_code') %}
The value come from grains and not sumaform. It's converted as `null` by salt and this condition work.

2021-07-21 02:02 UTC, maximenoel8 commented
I agree it should be added for the others providers. I will also need to add it for proxy.
I just want to see with you about this first PR and then I will add it to the others.

For the null variable. It was a big issue for me. I started by using `default = null` but when `server_registration_code` was not set, the cloud init will fail because the variable `server_registration_code` doesn't exist in this expression `%{ if server_registration_code != "null" }`

The null value is correctly converted in the salt/grain and so this expression work : 
`and grains['server_registration_code'] == 'null'`


To explain it simply, I want to skip all the scc register part if `server_registration_code` is not set ( cloud init description ). And skip all the internal repositories declaration if `server_registration_code` has a value ( salt execution ). If you have a better approach I'm open to it.

2021-07-21 03:22 UTC, maximenoel8 commented on backend_modules/aws/host/user_data.yaml
> +runcmd:
It looks good but I will also need to add a condition to `%{ if server_registration_code != "null" }` otherwise the registration and salt install will be executed for all the images if scc_registration_code is set.

Any idea how to write something like : 
`%{ if server_registration_code != "null" && image contains sles15sp }` ?

I didn't find a good documentation that describe how to use more complex condition in cloud-init .

2021-07-21 10:04 UTC, rjmateus commented on modules/base/variables.tf
> +  default     = "null"
I think you should use null type as default value in here.
One possible solution is check the value before passing it to cloud init template. I will add a comment with a proposed solution.

2021-07-21 10:08 UTC, rjmateus commented on backend_modules/aws/host/user_data.yaml
> +runcmd:
My idea was keep the outer if with the `%{ if server_registry_code != "null" }` and skip the all code block if the variable was not defined.
This code proposal could replace only the runcmd sections.

2021-07-21 11:13 UTC, moio commented
>     * the case where a package is being updated at SCC right now

At least this one is not a concern, infrastructure is there to make ample bandwidth available.

2021-07-22 03:05 UTC, maximenoel8 commented on backend_modules/aws/host/user_data.yaml
> +runcmd:
Yes I understand but the first runcmd outside of the image check will be executed for all the image if the SCC registration code is set.

2021-07-22 09:16 UTC, rjmateus commented on backend_modules/aws/host/user_data.yaml
> +runcmd:
Good point. in This case, I would say keep the code as it is right now :)

2021-07-27 02:02 UTC, merged